"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/Button";
import { Field, TextArea, TextInput } from "@/components/ui/Field";
import { Modal } from "@/components/ui/Modal";
import type { EnrichedCandidate, InterviewMeeting, RecruitmentLog } from "@/types/recruitment";

function bangkokInputValue(value: string) {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Bangkok", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(value));
  const pick = (type: string) => parts.find((part) => part.type === type)?.value ?? "00";
  return `${pick("year")}-${pick("month")}-${pick("day")}T${pick("hour")}:${pick("minute")}`;
}

export function TeamsInterviewComposer({ candidate, stage, meeting, busy, onClose, onSave }: { candidate: EnrichedCandidate | null; stage: RecruitmentLog | null; meeting?: InterviewMeeting | null; busy: boolean; onClose: () => void; onSave: (payload: Record<string, unknown>) => Promise<void> }) {
  const [dateTime, setDateTime] = useState(""), [duration, setDuration] = useState("60"), [emails, setEmails] = useState(""), [note, setNote] = useState(""), [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!stage) return; setDateTime(meeting ? bangkokInputValue(meeting.starts_at) : ""); setDuration(meeting ? String(Math.max(15, Math.round((Date.parse(meeting.ends_at) - Date.parse(meeting.starts_at)) / 60000))) : "60"); setEmails(meeting?.interviewer_emails.join(", ") ?? ""); setNote(meeting?.note ?? ""); setError(null); }, [meeting, stage]);
  async function save(operation: "create" | "reschedule" | "cancel") { if (!candidate || !stage) return; if (operation !== "cancel" && (!dateTime || !emails.trim())) return setError("Date, time, and interviewer email are required."); const start = new Date(`${dateTime}:00+07:00`), minutes = Number(duration); if (operation !== "cancel" && (!Number.isInteger(minutes) || minutes < 15)) return setError("Duration must be at least 15 minutes."); setError(null); await onSave({ operation, meeting_id: meeting?.meeting_id, candidate_id: candidate.candidate_id, stage_instance_id: stage.stage_instance_id, starts_at: start.toISOString(), ends_at: new Date(start.getTime() + minutes * 60000).toISOString(), interviewer_emails: emails.split(/[,;\n]/).map((value) => value.trim()).filter(Boolean), note }); }
  return <Modal open={Boolean(stage)} title={meeting ? "Manage Teams interview" : "Schedule Teams interview"} onClose={onClose} width="max-w-xl"><div className="grid gap-3"><p className="rounded-md bg-lightgray p-3 text-sm text-slate"><strong className="text-navy">{candidate?.name}</strong> · {stage?.recruitment_process} · Invitations are sent from the shared HR mailbox.</p>{candidate?.email ? null : <p role="alert" className="text-sm font-semibold text-scarlet">Candidate email is required before scheduling.</p>}<Field label="Bangkok date and time"><TextInput type="datetime-local" value={dateTime} onChange={(event) => setDateTime(event.target.value)} disabled={busy || meeting?.status === "cancelled"} /></Field><Field label="Duration (minutes)"><TextInput type="number" min="15" step="15" value={duration} onChange={(event) => setDuration(event.target.value)} disabled={busy || meeting?.status === "cancelled"} /></Field><Field label="Interviewer emails"><TextArea rows={3} value={emails} onChange={(event) => setEmails(event.target.value)} placeholder="manager@example.com, panel@example.com" disabled={busy || meeting?.status === "cancelled"} /></Field><Field label="Meeting note (optional)"><TextArea rows={3} value={note} onChange={(event) => setNote(event.target.value)} disabled={busy || meeting?.status === "cancelled"} /></Field>{error ? <p role="alert" className="text-sm font-semibold text-scarlet">{error}</p> : null}<div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Close</Button>{meeting && meeting.status !== "cancelled" ? <Button type="button" variant="secondary" disabled={busy} onClick={() => save("cancel")}>Cancel meeting</Button> : null}{meeting?.status === "cancelled" ? null : <Button type="button" disabled={busy || !candidate?.email} onClick={() => save(meeting ? "reschedule" : "create")}>{busy ? "Saving..." : meeting ? "Reschedule Teams interview" : "Schedule Teams interview"}</Button>}</div></div></Modal>;
}
