import type { DashboardReportContext } from "@/components/dashboard/DashboardPortal";
import { riskCopy } from "@/components/dashboard/risk-copy";
import { processStageLabel } from "./i18n/dictionary";
import type { DashboardTableSpec, ReportExportSnapshot, WorkbookCell } from "./dashboard-workbook";
import type { VacancyRiskReport, VacancyRiskRow } from "./vacancy-risk-report";
import type { StageBottleneckReport, WaitingRecord } from "./stage-bottleneck-report";
const date = (value: string | null): Date | null => value ? new Date(`${value}T00:00:00Z`) : null;
function table(id: string, title: string, headers: string[], rows: WorkbookCell[][], formats: Record<number, string> = {}): DashboardTableSpec {
  return { id, title, description: title, columns: headers.map((label, i) => ({ key: `col${i}`, label, width: 22, format: formats[i] })), rows };
}
function snapshot(context: DashboardReportContext, reportId: "risk" | "bottlenecks", filename: string, scope: string, summary: DashboardTableSpec[], source: DashboardTableSpec[]): ReportExportSnapshot {
  const th = context.language === "th";
  return { reportId, filename: `${filename}.xlsx`, generatedAt: new Date().toISOString(), language: context.language, scope,
    sheets: [{ id: "summary", title: th ? "ข้อมูลสรุป" : "Summary Data", tables: [...summary, table("readme", th ? "คำแนะนำ" : "Guide", [th ? "หัวข้อ" : "Field", th ? "รายละเอียด" : "Value"], [
      [th ? "ขอบเขต" : "Scope", scope], [th ? "ประวัติ" : "History", riskCopy(context.language)("history")],
      [th ? "สร้างเมื่อ (กรุงเทพฯ)" : "Generated (Bangkok)", new Intl.DateTimeFormat(th ? "th-TH" : "en-GB", { dateStyle: "short", timeStyle: "medium", timeZone: "Asia/Bangkok" }).format(new Date())],
      [th ? "วิธีนับ" : "Counting", th ? "วันปฏิทิน มัธยฐานและ P90 ใช้ PERCENTILE.INC ค่าว่างหมายถึงไม่ทราบ ตัวกรองรายละเอียดไม่เปลี่ยนยอดรวม" : "Calendar days; median/P90 use PERCENTILE.INC. Blank means unavailable. Detail filters do not change headline totals."],
      [th ? "สิทธิ์" : "Access", th ? "ข้อมูลผู้สมัครมาจากรายการปฏิบัติงานที่มีสิทธิ์เท่านั้น ไม่ส่งออกข้อมูลติดต่อหรือหมายเหตุ" : "Candidate identity comes only from authorized operational records. No contact information or free-text notes."],
      [th ? "เกณฑ์" : "Rules", th ? "ใกล้ SLA: 0–7 วัน เกิน SLA: ต่ำกว่า 0 ไม่ทราบ SLA ไม่อยู่ในตัวหารความเสี่ยง การ์ดใช้อัตราคงค้างทั้งหมด อัตราสำคัญที่เสี่ยงใช้อัตราสำคัญคงค้างทั้งหมด คิวหนึ่งแถวต่อผู้สมัคร เวลาสำเร็จหนึ่งแถวต่อรอบที่ถูกต้อง" : "Near SLA: 0–7 days; overdue: negative. Unknown SLA excluded from exposure denominator. Risk cards use all open headcount; Priority at risk uses all open priority headcount. Queue: one candidate. Durations: each valid completed attempt."]
    ])] }, { id: "source", title: th ? "ข้อมูลต้นทาง" : "Source Data", tables: source }] };
}
export function buildRiskExport(context: DashboardReportContext, report: VacancyRiskReport, groups: ReturnType<typeof import("./vacancy-risk-report").riskGroups>, visible: VacancyRiskRow[], localScope: string) {
  const t = riskCopy(context.language), th = context.language === "th", period = th ? "ช่วง" : "Period", current = th ? "ปัจจุบัน" : "Current", prior = th ? "เปรียบเทียบ" : "Prior";
  const keys = ["open", "track", "near", "overdue", "unknown", "priority", "priorityOpen", "exposure"] as const;
  const metrics = table("metrics", t("health"), [th ? "ตัวชี้วัด" : "Metric", current, prior, th ? "ผลต่าง" : "Change", th ? "หน่วยผลต่าง" : "Change unit", th ? "ฐานปัจจุบัน" : "Current denominator", th ? "สัดส่วนปัจจุบัน" : "Current share", th ? "ฐานเปรียบเทียบ" : "Prior denominator", th ? "สัดส่วนเปรียบเทียบ" : "Prior share"], keys.map(key => {
    const denominator = key === "priority" ? report.totals.priorityOpen : key === "near" || key === "overdue" ? report.totals.open : null;
    const priorDenominator = !report.prior ? null : key === "priority" ? report.prior.totals.priorityOpen : key === "near" || key === "overdue" ? report.prior.totals.open : null;
    return [t(key), report.totals[key], report.prior?.totals[key] ?? null, report.prior && report.totals[key] !== null && report.prior.totals[key] !== null ? (report.totals[key]! - report.prior.totals[key]!) * (key === "exposure" ? 100 : 1) : null, key === "exposure" ? th ? "จุดเปอร์เซ็นต์" : "percentage points" : th ? "อัตรา" : "headcount", denominator, denominator ? report.totals[key]! / denominator : null, priorDenominator, priorDenominator ? report.prior!.totals[key]! / priorDenominator : null];
  }), { 6: "0.0%", 8: "0.0%" });
  const groupTable = table("groups", t("distribution"), [t("group"), t("track"), t("approaching"), t("overdue"), t("unknown"), t("total"), t("exposure")], groups.map(row => [row.name, row.track, row.near, row.overdue, row.unknown, row.open, row.exposure]), { 6: "0.0%" });
  const trends = table("trends", th ? "แนวโน้ม" : "Trends", [t("asOf"), t("open"), t("overdue"), t("near"), t("priority"), t("exposure")], report.trends.map(row => [date(row.date), row.open, row.overdue, row.near, row.priority, row.exposure]), { 0: "dd/mm/yyyy", 5: "0.0%" });
  const headers = [period, th ? "รหัสใบขออัตรา" : "Requisition ID", t("position"), t("site"), t("department"), t("level"), t("pic"), t("approved"), t("open"), th ? "อัตราที่ครอบคลุม" : "Covered HC", t("status"), th ? "เริ่ม SLA" : "SLA start", th ? "เริ่มใหม่" : "Restart", th ? "กำหนด SLA" : "Deadline", t("age"), t("remaining"), th ? "สำคัญ" : "Priority", th ? "อยู่ในรายการที่กรอง" : "Visible action row"];
  const records = [...report.rows.map(row => ({ row, period: current })), ...(report.prior?.rows ?? []).map(row => ({ row, period: prior }))];
  const sources = table("requisitions", t("requisitions"), headers, records.map(({ row, period: p }) => [p, row.requisition.doc_id, row.requisition.position, row.requisition.site, row.requisition.department, row.requisition.level, row.requisition.person_in_charge, row.requisition.head_count, row.open, row.covered, t(row.kind), date(row.start), date(row.restart), date(row.deadline), row.age, row.remaining, Number(Boolean(row.requisition.is_priority)), Number(p === current && visible.some(v => v.requisition.doc_id === row.requisition.doc_id))]), { 11: "dd/mm/yyyy", 12: "dd/mm/yyyy", 13: "dd/mm/yyyy" });
  const coverage = table("coverage", th ? "การครอบคลุมและเปิดใหม่" : "Offer coverage / reopening", [period, th ? "รหัสใบขออัตรา" : "Requisition ID", th ? "รหัสข้อเสนอ" : "Offer ID", th ? "วันที่ตอบรับ" : "Accepted", th ? "วันที่เปิดใหม่" : "Reopened", th ? "นับครอบคลุม" : "Covered contribution", th ? "เหตุผล" : "Explanation"], report.coverage.map(row => [row.period === "Current" ? current : prior, row.docId, String(row.offerId), date(row.accepted), date(row.reopened), row.covered, th ? ({ Covered: "ครอบคลุมอัตรา", "Headcount cap": "เกินอัตราอนุมัติ", "No-show reopening": "เปิดใหม่หลังไม่เริ่มงาน", "Not effective at snapshot": "ไม่มีผล ณ วันรายงาน" } as Record<string, string>)[row.reason] : row.reason]), { 3: "dd/mm/yyyy", 4: "dd/mm/yyyy" });
  return snapshot(context, "risk", `vacancy-risk-${report.asOf}`, `${context.summary} · ${t("asOf")} ${report.asOf} · ${localScope} · ${t("compared")} ${report.priorRange.start} – ${report.priorRange.end}`, [metrics, groupTable, trends], [sources, coverage]);
}
export function buildBottleneckExport(context: DashboardReportContext, report: StageBottleneckReport, visible: WaitingRecord[], localScope: string) {
  const t = riskCopy(context.language), th = context.language === "th", label = (en: string, thai: string) => th ? thai : en;
  const keys = ["waiting", "median", "overdue", "longest", "unavailable"] as const;
  const metrics = table("metrics", t("stageTitle"), [label("Metric", "ตัวชี้วัด"), label("Current", "ปัจจุบัน"), label("Prior", "เปรียบเทียบ"), label("Change", "ผลต่าง"), label("Change unit", "หน่วยผลต่าง")], keys.map(key => {
    const current = report.metrics[key], priorValue = report.prior && !(key === "overdue" && (report.metrics.unavailable || report.prior.metrics.unavailable)) ? report.prior.metrics[key] : null;
    return [t(key), current, priorValue, current !== null && priorValue !== null ? current - priorValue : null, key === "median" || key === "longest" ? t("days") : label("candidates", "ผู้สมัคร")];
  }));
  const stats = table("stats", t("duration"), [t("stage"), t("sample"), t("median"), "P90", t("waiting"), t("oldest")], report.stages.map(row => [processStageLabel(context.language, row.stage), row.sample, row.median, row.p90, row.waiting, row.oldest]), { 2: "0.0", 3: "0.0" });
  const primary = table("primary", t("primary"), [t("stage"), t("median"), "P90", t("waiting"), t("oldest")], report.primary ? [[processStageLabel(context.language, report.primary.stage), report.primary.median, report.primary.p90, report.primary.waiting, report.primary.oldest]] : [], { 1: "0.0", 2: "0.0" });
  const trends = table("trends", label("Trends", "แนวโน้ม"), [t("asOf"), t("waiting"), t("median"), t("past"), t("longest")], report.trends.map(row => [date(row.date), row.waiting, row.median, row.overdue, row.longest]), { 0: "dd/mm/yyyy", 2: "0.0" });
  const candidates = new Map(context.data.candidates.map(row => [row.candidate_id, row]));
  const exclusions: Record<string, string> = { "Outcome-only legacy record": "ข้อมูลเดิมมีเฉพาะผล ไม่มีวันที่เข้าจริง", "Inferred or clamped migration date": "วันที่ย้ายข้อมูลเป็นค่าคาดเดาหรือปรับลำดับ", "Missing or invalid entry date": "ไม่มีวันที่เข้าหรือวันที่ไม่ถูกต้อง", "Missing or invalid outcome date": "ไม่มีวันที่ผลหรือวันที่ไม่ถูกต้อง", "Outcome precedes entry": "วันที่ผลก่อนวันที่เข้า" };
  const instances = table("instances", label("Stage attempts", "รอบขั้นตอน"), [label("Activity ID", "รหัสกิจกรรม"), label("Candidate ID", "รหัสผู้สมัคร"), t("candidate"), t("stage"), label("Round", "รอบ"), label("Entry", "วันที่เข้า"), label("Outcome", "วันที่ผล"), label("Result", "ผล"), label("Duration", "เวลา"), label("Current contribution", "นับช่วงปัจจุบัน"), label("Prior contribution", "นับช่วงเปรียบเทียบ"), label("Exclusion", "เหตุผลไม่นับ"), label("Scoped requisitions", "ใบขออัตราในขอบเขต")], report.instances.map(row => [String(row.logId), row.candidateId, candidates.get(row.candidateId)?.name ?? null, processStageLabel(context.language, row.stage), row.round, date(row.entry), date(row.outcome), row.result, row.duration, Number(report.completions.some(record => record.id === row.id && !record.exclusion)), Number(Boolean(report.prior?.completions.some(record => record.id === row.id && !record.exclusion))), row.exclusion ? th ? exclusions[row.exclusion] ?? row.exclusion : row.exclusion : null, report.contexts.get(row.candidateId)?.map(req => req.doc_id).join(", ") ?? ""]), { 5: "dd/mm/yyyy", 6: "dd/mm/yyyy" });
  const queues = [...report.waiting.map(row => ({ row, period: label("Current", "ปัจจุบัน") })), ...(report.prior?.waiting ?? []).map(row => ({ row, period: label("Prior", "เปรียบเทียบ") }))];
  const waiting = table("waiting", t("queue"), [label("Period", "ช่วง"), label("Candidate ID", "รหัสผู้สมัคร"), t("candidate"), t("stage"), t("waiting"), t("due"), t("status"), t("position"), t("pic"), label("Visible action row", "อยู่ในรายการที่กรอง"), label("Conflicting pending", "รายการรอขัดแย้ง")], queues.map(({ row, period }) => [period, row.candidate.candidate_id, row.candidate.name, processStageLabel(context.language, row.instance.stage), row.wait, row.status === "unavailable" ? null : date(row.instance.due), t(row.status), row.requisitions.map(req => `${req.doc_id} · ${req.position} · ${req.site} · ${req.department}`).join("\n"), [...new Set(row.requisitions.map(req => req.person_in_charge).filter(Boolean))].join(", "), Number(period === label("Current", "ปัจจุบัน") && visible.some(record => record.candidate.candidate_id === row.candidate.candidate_id)), Number(row.conflict)]), { 5: "dd/mm/yyyy" });
  return snapshot(context, "bottlenecks", `stage-bottlenecks-${report.start}-to-${report.asOf}`, `${context.summary} · ${t("asOf")} ${report.asOf} · ${t("channel")}: ${report.channel} · ${localScope} · ${t("compared")} ${report.priorRange.start} – ${report.priorRange.end}`, [metrics, stats, primary, trends], [instances, waiting]);
}
