"use client";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { Field, SelectInput, TextArea, TextInput } from "@/components/ui/Field";
import { normalizeRejectionLetterVariables, REJECTION_LETTER_VARIABLES, validateLetterTemplate } from "@/lib/rejection-letter";
import { supabase } from "@/lib/supabase/client";
import type { RejectionLetterTemplate } from "@/types/recruitment";

export function RejectionLetterTemplateAdmin({ templates, onChanged }: { templates: RejectionLetterTemplate[]; onChanged: () => Promise<unknown> }) {
  const [editing, setEditing] = useState<RejectionLetterTemplate | null>(null); const [editorOpen, setEditorOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [form, setForm] = useState({ name: "", language: "th", subject_template: "", body_template: "", active: true });
  function open(template?: RejectionLetterTemplate) { setEditing(template ?? null); setEditorOpen(true); setForm(template ? { name: template.name, language: template.language, subject_template: normalizeRejectionLetterVariables(template.subject_template), body_template: normalizeRejectionLetterVariables(template.body_template), active: template.active } : { name: "", language: "th", subject_template: "", body_template: "", active: true }); setError(null); }
  function closeEditor() { setEditing(null); setEditorOpen(false); setError(null); }
  async function save() { const normalizedForm = { ...form, subject_template: normalizeRejectionLetterVariables(form.subject_template), body_template: normalizeRejectionLetterVariables(form.body_template) }; const invalid = [...validateLetterTemplate(normalizedForm.subject_template), ...validateLetterTemplate(normalizedForm.body_template)]; if (invalid.length) return setError(`Unknown or incomplete variable: ${[...new Set(invalid)].join(", ")}`); if (!supabase) return setError("Sign in before saving."); setBusy(true); try { const { data } = await supabase.auth.getSession(); const response = await fetch("/api/rejection-letters/templates", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${data.session?.access_token ?? ""}` }, body: JSON.stringify({ ...normalizedForm, template_id: editing?.template_id }) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error ?? "Could not save template."); await onChanged(); closeEditor(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Could not save template."); } finally { setBusy(false); } }
  return <section><div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="font-semibold text-navy">Send rejection letter format</h3><p className="text-sm text-slate">Only active formats are available to recruiters.</p></div><Button type="button" size="sm" onClick={() => open()}>New format</Button></div>{editorOpen ? <div className="grid gap-3 rounded-md border border-[#D7DEE8] bg-lightgray/60 p-3"><Field label="Format name"><TextInput value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><div className="grid gap-3 md:grid-cols-2"><Field label="Letter language"><SelectInput value={form.language} onChange={(event) => setForm({ ...form, language: event.target.value })}><option value="th">Thai</option><option value="en">English</option></SelectInput></Field><label className="mt-6 flex items-center gap-2 text-sm font-semibold text-slate"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} />Active</label></div><Field label="Subject"><TextInput value={form.subject_template} onChange={(event) => setForm({ ...form, subject_template: event.target.value })} /></Field><Field label="Body"><TextArea rows={6} value={form.body_template} onChange={(event) => setForm({ ...form, body_template: event.target.value })} /></Field><p className="text-xs text-slate">Variables: {REJECTION_LETTER_VARIABLES.join(", ")}</p>{error ? <p role="alert" className="text-sm font-semibold text-scarlet">{error}</p> : null}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={closeEditor}>Cancel</Button><Button type="button" disabled={busy} onClick={save}>{busy ? "Saving..." : "Save format"}</Button></div></div> : null}<div className="grid gap-2">{templates.map((template) => <div key={template.template_id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-[#D7DEE8] bg-white p-3"><span className="min-w-0 text-sm font-semibold text-navy">{template.name} <span className="font-medium text-slate">· {template.language.toUpperCase()} · v{template.version} · {template.active ? "Active" : "Archived"}</span></span><Button type="button" size="sm" variant="secondary" onClick={() => open(template)}>Edit</Button></div>)}</div></section>;
}
