-- Canonical declarative schema source. Edit this file set, not historical migrations.

create table if not exists public.app_id_counters (
  entity text primary key,
  next_value integer not null default 1 check (next_value > 0)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  nickname text,
  site text,
  role text not null default 'viewer' check (role in ('system_admin', 'admin_recruiter', 'site_recruiter', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.requisitions (
  doc_id text primary key,
  pr_approved_date date,
  site text not null,
  position text not null,
  department text not null,
  section text,
  level text,
  head_count integer not null default 1 check (head_count > 0),
  person_in_charge text,
  line_manager text,
  request_type text not null default 'New' check (request_type in ('New', 'Replacement')),
  replacement_names text,
  status text not null default 'ongoing' check (status in ('ongoing', 'filled', 'cancel')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.requisition_logs (
  log_id bigint generated by default as identity primary key,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  log_date date not null,
  status text not null check (status in ('ongoing', 'filled', 'cancel')),
  remark text,
  created_at timestamptz not null default now()
);

create table if not exists public.position_groups (
  group_id text primary key,
  group_position text not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_groups (
  doc_group_id text primary key,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  group_id text references public.position_groups(group_id) on delete set null,
  group_position text not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (doc_id, group_id)
);

create table if not exists public.candidates (
  candidate_id text primary key,
  name text not null,
  phone_no text,
  doc_group_id text not null references public.document_groups(doc_group_id) on delete restrict,
  channel text,
  ref_name text,
  first_contact_date date,
  candidate_folder_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recruitment_logs (
  log_id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  log_date date not null,
  recruitment_process text not null check (
    recruitment_process in (
      'First Contact',
      'Phone Screen',
      'HR Interview',
      'Line Interview',
      'Test',
      'Reference Check',
      'Offer',
      'Rejected',
      'Withdrawn'
    )
  ),
  round integer not null default 1 check (round > 0),
  interviewer text,
  result smallint check (result in (0, 1)),
  remark text,
  created_at timestamptz not null default now()
);

create table if not exists public.offers (
  offer_id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  accepted_date date,
  first_working_date date,
  remark text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (candidate_id, doc_id)
);

create table if not exists public.sourcing_weekly_updates (
  group_id text not null references public.position_groups(group_id) on delete cascade,
  week_start date not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
  applicants_fb integer not null default 0 check (applicants_fb >= 0),
  applicants_jobthai integer not null default 0 check (applicants_jobthai >= 0),
  applicants_jobtopgun integer not null default 0 check (applicants_jobtopgun >= 0),
  applicants_jobdb integer not null default 0 check (applicants_jobdb >= 0),
  applicants_linkedin integer not null default 0 check (applicants_linkedin >= 0),
  applicants_walkin integer not null default 0 check (applicants_walkin >= 0),
  applicants_referral integer not null default 0 check (applicants_referral >= 0),
  applicants_others integer not null default 0 check (applicants_others >= 0),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (group_id, week_start)
);

create table if not exists public.vacancy_weekly_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  week_start date not null,
  waterfall_category text not null check (waterfall_category in ('Week Start', 'Open', 'Filled', 'Total')),
  site text not null,
  request_type text not null check (request_type in ('New', 'Replacement')),
  vacancy_count integer not null default 0,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_start, waterfall_category, site, request_type)
);

create table if not exists public.change_logs (
  log_id bigint generated by default as identity primary key,
  entity text not null,
  entity_id text not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  old_data jsonb,
  new_data jsonb
);
