-- Canonical declarative schema source. Edit this file set, not historical migrations.

create table if not exists public.app_id_counters (
  entity text primary key,
  next_value integer not null default 1 check (next_value > 0)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  nickname text,
  site text,
  role text not null default 'viewer' check (role in ('system_admin', 'admin_recruiter', 'site_recruiter', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.requisitions (
  doc_id text primary key,
  pr_approved_date date,
  site text not null,
  position text not null,
  department text not null,
  section text,
  level text,
  head_count integer not null default 1 check (head_count > 0),
  person_in_charge text,
  line_manager text,
  request_type text not null default 'New' check (request_type in ('New', 'Replacement')),
  replacement_names text,
  status text not null default 'ongoing' check (status in ('ongoing', 'filled', 'cancel')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.requisition_logs (
  log_id bigint generated by default as identity primary key,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  log_date date not null,
  status text not null check (status in ('ongoing', 'filled', 'cancel')),
  remark text,
  created_at timestamptz not null default now()
);

create table if not exists public.position_groups (
  group_id text primary key,
  group_position text not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_jobbkk boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_groups (
  doc_group_id text primary key,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  group_id text references public.position_groups(group_id) on delete set null,
  group_position text not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_jobbkk boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (doc_id, group_id)
);

create table if not exists public.candidates (
  candidate_id text primary key,
  name text not null,
  nickname text,
  phone_no text,
  -- Candidates are managed by group_id. doc_group_id is an optional legacy anchor
  -- for older views and becomes null when the final requisition is unmatched.
  doc_group_id text references public.document_groups(doc_group_id) on delete set null,
  group_id text not null references public.position_groups(group_id) on delete restrict,
  channel text,
  ref_name text,
  first_contact_date date,
  candidate_folder_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.candidate_references (
  reference_id uuid primary key default gen_random_uuid(),
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  reference_name text not null check (btrim(reference_name) <> ''),
  relationship text not null check (btrim(relationship) <> ''),
  channel_type text not null check (channel_type in ('phone', 'email', 'line', 'other')),
  channel_value text not null check (btrim(channel_value) <> ''),
  other_channel_label text,
  status text not null default 'available' check (status in ('available', 'unavailable', 'archived')),
  status_reason text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((channel_type = 'other' and nullif(btrim(other_channel_label), '') is not null) or (channel_type <> 'other' and other_channel_label is null)),
  check ((status = 'available' and status_reason is null) or (status in ('unavailable', 'archived') and nullif(btrim(status_reason), '') is not null))
);

create table if not exists public.candidate_reference_checks (
  check_id uuid primary key default gen_random_uuid(),
  reference_id uuid not null unique references public.candidate_references(reference_id) on delete cascade,
  checked_date date not null,
  duration_minutes integer not null check (duration_minutes > 0),
  conversation_summary text not null check (btrim(conversation_summary) <> ''),
  checked_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recruitment_logs (
  log_id bigint generated by default as identity primary key,
  stage_instance_id uuid not null default gen_random_uuid() unique,
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  log_date date not null,
  recruitment_process text not null,
  round integer not null default 1 check (round > 0),
  interviewer text,
  result smallint check (result in (0, 1)),
  remark text,
  estimated_action_date date,
  outcome_date date,
  outcome_interviewer text,
  outcome_remark text,
  outcome_recorded_at timestamptz,
  pending_edited_at timestamptz,
  pending_edited_by uuid references auth.users(id) on delete set null,
  record_origin text not null default 'user' check (record_origin in ('user', 'auto', 'migration', 'correction')),
  migration_note text,
  superseded_at timestamptz,
  superseded_by_stage_instance_id uuid references public.recruitment_logs(stage_instance_id) deferrable initially deferred,
  superseded_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    recruitment_process in ('Phone Screen', 'HR Interview', 'Line Interview', 'Test', 'Reference Check', 'Offer')
    or (record_origin = 'migration' and superseded_at is not null)
  ),
  check (
    (result is null and outcome_date is null and outcome_interviewer is null and outcome_remark is null and outcome_recorded_at is null)
    or (result in (0, 1) and outcome_date is not null and outcome_recorded_at is not null)
  ),
  constraint recruitment_logs_estimated_action_date_order check (estimated_action_date is null or estimated_action_date >= log_date),
  check (result is null or outcome_date >= log_date),
  check (
    (superseded_at is null and superseded_by_stage_instance_id is null and superseded_reason is null)
    or (
      superseded_at is not null
      and superseded_by_stage_instance_id is not null
      and superseded_reason is not null
      and superseded_by_stage_instance_id <> stage_instance_id
    )
    or (
      superseded_at is not null
      and superseded_by_stage_instance_id is null
      and superseded_reason is not null
      and record_origin = 'migration'
      and migration_note like '%legacy-only archive without canonical replacement%'
    )
  )
);

create table if not exists public.offers (
  offer_id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  accepted_date date,
  first_working_date date,
  start_confirmation text check (start_confirmation in ('started', 'did_not_start')),
  start_confirmed_at timestamptz,
  start_confirmed_by uuid references public.profiles(id),
  start_confirmation_reason text,
  constraint offers_start_confirmation_check check (
    (start_confirmation is null and start_confirmed_at is null and start_confirmed_by is null and start_confirmation_reason is null)
    or (start_confirmation = 'started' and start_confirmed_at is not null and start_confirmed_by is not null and start_confirmation_reason is null)
    or (start_confirmation = 'did_not_start' and start_confirmed_at is not null and start_confirmed_by is not null and nullif(btrim(start_confirmation_reason), '') is not null)
  ),
  remark text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (candidate_id, doc_id)
);
create index if not exists offers_start_confirmation_due_idx on public.offers (first_working_date) where accepted_date is not null and first_working_date is not null and start_confirmation is null;

create table if not exists public.sourcing_weekly_updates (
  group_id text not null references public.position_groups(group_id) on delete cascade,
  week_start date not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_jobbkk boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
    applicants_fb integer check (applicants_fb >= 0),
    applicants_jobthai integer check (applicants_jobthai >= 0),
    applicants_jobtopgun integer check (applicants_jobtopgun >= 0),
    applicants_jobdb integer check (applicants_jobdb >= 0),
    applicants_jobbkk integer check (applicants_jobbkk >= 0),
    applicants_linkedin integer check (applicants_linkedin >= 0),
    applicants_walkin integer check (applicants_walkin >= 0),
    applicants_referral integer check (applicants_referral >= 0),
    applicants_others integer check (applicants_others >= 0),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (group_id, week_start)
);

create table if not exists public.vacancy_weekly_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  week_start date not null,
  waterfall_category text not null check (waterfall_category in ('Week Start', 'Open', 'Filled', 'Total')),
  site text not null,
  request_type text not null check (request_type in ('New', 'Replacement')),
  vacancy_count integer not null default 0,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_start, waterfall_category, site, request_type)
);

create table if not exists public.change_logs (
  log_id bigint generated by default as identity primary key,
  entity text not null,
  entity_id text not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  old_data jsonb,
  new_data jsonb
);
