"use client";
import { useMemo, useRef, useState } from "react";
import { AlertTriangle, Clock3, UsersRound, Search, ChevronRight, X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { CommandSelector } from "@/components/ui/CommandSelector";
import { processStageLabel } from "@/lib/i18n/dictionary";
import { buildStageBottleneckReport, BOTTLENECK_STAGES, type DeadlineStatus } from "@/lib/stage-bottleneck-report";
import { previousPerformanceRange } from "@/lib/recruitment-performance";
import { todayDate } from "@/lib/sla";
import { buildBottleneckExport } from "@/lib/risk-bottleneck-export";
import type { DashboardReportContext } from "./DashboardPortal";
import { riskCopy } from "./risk-copy";
import { Comparison, MiniTrend, RiskReportFrame } from "./RiskReportFrame";
import styles from "./risk-reports.module.css";
export function StageBottleneckView({ context }: { context: DashboardReportContext }) {
  const { language, data, requisitions, preferences: p, onPreferencesChange: change, range } = context, t = riskCopy(language), actionRef = useRef<HTMLElement>(null);
  const [page, setPage] = useState(0);
  const report = useMemo(() => buildStageBottleneckReport(data, requisitions, range, todayDate(), previousPerformanceRange(p.period, { start: range.start, end: range.end < todayDate() ? range.end : todayDate() }), p.funnelChannel), [data, requisitions, range, p.period, p.funnelChannel]);
  const status = p.queueStatus === "auto" ? report.metrics.overdue ? "overdue" : "all" : p.queueStatus;
  const visible = report.waiting.filter(row => (status === "all" || row.status === status) && (!p.queueStage || row.instance.stage === p.queueStage) && (!p.queuePic || row.requisitions.some(req => req.person_in_charge === p.queuePic)) && (!p.queueSearch || [row.candidate.candidate_id, row.candidate.name, row.instance.stage, ...row.requisitions.map(req => `${req.position} ${req.site} ${req.department}`)].join(" ").toLocaleLowerCase().includes(p.queueSearch.toLocaleLowerCase())));
  const maxPage = Math.max(0, Math.ceil(visible.length / 20) - 1), currentPage = Math.min(page, maxPage);
  const stageLabel = (stage: typeof BOTTLENECK_STAGES[number]) => processStageLabel(language, stage);
  const fmt = (value: number | null) => value === null ? "—" : `${Number(value.toFixed(1))}${language === "th" ? " วัน" : "d"}`;
  function patch(values: Parameters<typeof change>[0]) { change(values); setPage(0); }
  function drill(stage: string) { patch({ queueStage: stage, queueStatus: "all" }); requestAnimationFrame(() => { actionRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" }); actionRef.current?.focus(); }); }
  const maxDuration = Math.max(5, ...report.stages.map(row => row.p90 ?? 0)), axisMax = Math.ceil(maxDuration / 5) * 5;
  const maxQueue = Math.max(1, ...report.stages.map(row => row.waiting));
  const localScope = `${t("status")}: ${status === "all" ? t("all") : t(status as DeadlineStatus)} · ${t("stage")}: ${p.queueStage || t("all")} · ${t("pic")}: ${p.queuePic || t("all")} · ${t("search")}: ${p.queueSearch || "—"}`;
  function render(exportMode: boolean) { return <div className={styles.content}>
    <div className={styles.stageToolbar}>{!exportMode ? <label className={styles.inlineField}><span>{t("channel")}</span><CommandSelector typography="normal" ariaLabel={t("channel")} emptyLabel={t("all")} value={p.funnelChannel} options={[{ value: "all", label: t("all") }, ...[...new Set(data.candidates.map(row => row.channel ?? "Others"))].sort().map(value => ({ value, label: value }))]} onValueChange={value => change({ funnelChannel: value })} /></label> : <p>{t("channel")}: {p.funnelChannel}</p>}<small>{t("asOf")} {report.asOf}</small></div>
    {report.future ? <p className={styles.notice}>{t("future")}</p> : null}
    {exportMode ? <div className={styles.stageKpis}>{(["waiting", "median", "overdue", "longest"] as const).map((key, i) => <section className={styles.stageKpi} key={key}>
      <span className={styles.kpiTop}><span className={`${styles.kpiIcon} ${i === 0 ? styles.blueSurface : i === 2 ? styles.amberSurface : styles.redSurface}`}>{i === 0 ? <UsersRound size={16} /> : i === 2 ? <AlertTriangle size={16} /> : <Clock3 size={16} />}</span><strong>{t(key === "overdue" ? report.metrics.unavailable ? "knownPast" : "past" : key)}</strong></span>
      <b className={styles.summaryValue} data-bottleneck-metric={key}>{key === "median" || key === "longest" ? fmt(report.metrics[key]) : report.metrics[key]}</b>
      <small className={styles.summaryContext}>{key === "median" || key === "longest" ? t("days") : t("candidate")}</small>
      <MiniTrend values={report.trends.map(row => row[key])} label={`${t(key === "overdue" ? "past" : key)}: ${report.trends.map(row => `${row.date} ${row[key] ?? "—"}`).join(", ")}`} />
      <Comparison value={report.metrics[key]} prior={key === "overdue" && (report.metrics.unavailable || report.prior?.metrics.unavailable) ? null : report.prior?.metrics[key]} days={key === "median" || key === "longest"} range={report.priorRange} language={language} />
    </section>)}</div> : null}
    {report.metrics.unavailable ? <p className={styles.notice}>{t("unavailable")}: {report.metrics.unavailable}. {t("knownDue")}</p> : null}
    <section className={styles.bottleneckBanner}><AlertTriangle size={18} /><div className={styles.bannerTitle}><h3>{report.primary ? `${t("primary")}: ${stageLabel(report.primary.stage)}` : t("noPrimary")}</h3>{report.primary ? <p>{report.metrics.waiting ? (report.primary.waiting / report.metrics.waiting * 100).toFixed(1) : "0.0"}% · {t("waiting")} · {t("durationHint")}</p> : null}</div>{report.primary ? <><div><strong>{report.primary.waiting}</strong><small>{t("waiting")}</small></div><div><strong>{fmt(report.primary.median)}</strong><small>{t("median")}</small></div><div><strong>{fmt(report.primary.p90)}</strong><small>P90</small></div><div><strong>{fmt(report.primary.oldest)}</strong><small>{t("oldest")}</small></div><Button type="button" size="toolbar" variant="secondary" onClick={() => drill(report.primary!.stage)}>{t("viewCandidates")} <ChevronRight size={14} /></Button></> : null}</section>
    <div className={styles.twoColumns}>
      <section className={styles.panel}><header className={styles.sectionHead}><div><h3>{t("duration")}</h3><small>{t("durationHint")}</small></div></header><div className={styles.durationLegend}><span><i className={styles.medianDot} />{t("median")}</span><span><i className={styles.p90Dot} />P90</span></div><div className={styles.tableScroll}><table className={styles.durationTable}><thead><tr><th>{t("stage")}</th><th><div className={styles.axis}>{Array.from({ length: 5 }, (_, i) => <span key={i}>{Number((axisMax * i / 4).toFixed(1))}</span>)}</div></th><th>{t("median")}</th><th>P90</th><th>{t("sample")}</th></tr></thead><tbody>{report.stages.map(row => <tr key={row.stage} className={row.stage === report.primary?.stage ? styles.highlight : ""}><th><button type="button" onClick={() => drill(row.stage)}>{stageLabel(row.stage)}</button></th><td><div className={styles.durationPlot} title={`${t("sample")}: ${row.sample}${row.sample > 0 && row.sample < 5 ? ` · ${t("small")}` : ""}`} role="img" aria-label={`${stageLabel(row.stage)}, ${t("median")} ${fmt(row.median)}, P90 ${fmt(row.p90)}, N ${row.sample}`}>
        {row.median !== null && row.p90 !== null ? <><span className={styles.rangeLine} style={{ left: `${row.median / axisMax * 100}%`, width: `${(row.p90 - row.median) / axisMax * 100}%` }} /><span className={styles.medianDot} style={{ left: `${row.median / axisMax * 100}%` }} /><span className={styles.p90Dot} style={{ left: `${row.p90 / axisMax * 100}%` }} /></> : <span className={styles.note}>—</span>}
      </div></td><td>{fmt(row.median)}</td><td>{fmt(row.p90)}</td><td title={row.sample > 0 && row.sample < 5 ? t("small") : undefined}>{row.sample}{row.sample > 0 && row.sample < 5 ? " *" : ""}</td></tr>)}</tbody></table></div><p className={styles.note}>{t("excluded")}: {report.excluded} · {t("conflicts")}: {report.conflicts}</p></section>
      <section className={styles.panel}><header className={styles.sectionHead}><h3>{t("queue")}</h3></header><div className={styles.tableScroll}><table><thead><tr><th>{t("stage")}</th><th>{t("waiting")}</th><th>{t("oldest")}</th></tr></thead><tbody>{report.stages.map(row => <tr key={row.stage} className={row.stage === report.primary?.stage ? styles.highlight : ""}><th><button type="button" onClick={() => drill(row.stage)}>{stageLabel(row.stage)}</button></th><td><div className={styles.queueCount}><span className={styles.queueBar}><i style={{ width: `${row.waiting / maxQueue * 100}%` }} /></span><strong>{row.waiting}</strong></div></td><td>{fmt(row.oldest)}</td></tr>)}</tbody></table></div></section>
    </div>
    <section className={styles.panel} ref={exportMode ? undefined : actionRef} tabIndex={-1} aria-label={t("actions")}><header className={styles.sectionHead}><h3>{t("actions")} <small>({visible.length})</small></h3></header>
      {!exportMode ? <><div className={styles.queueFilters}><div className={styles.statusTabs} role="group" aria-label={t("status")}>{(["overdue", "today", "upcoming", "all", "unscheduled", "unavailable"] as const).filter(key => !["unscheduled", "unavailable"].includes(key) || report.waiting.some(row => row.status === key)).map(key => <button type="button" key={key} aria-pressed={status === key} className={status === key ? styles.selected : ""} onClick={() => patch({ queueStatus: key })}>{t(key)} <b>{key === "all" ? report.waiting.length : report.waiting.filter(row => row.status === key).length}</b></button>)}</div><label className={styles.search}><Search size={16} /><input aria-label={t("search")} placeholder={t("search")} value={p.queueSearch} onChange={event => patch({ queueSearch: event.target.value })} /></label><CommandSelector typography="normal" ariaLabel={t("stage")} emptyLabel={t("all")} value={p.queueStage} options={[{ value: "", label: `${t("stage")} · ${t("all")}` }, ...BOTTLENECK_STAGES.map(value => ({ value, label: stageLabel(value) }))]} onValueChange={value => patch({ queueStage: value })} /><CommandSelector typography="normal" ariaLabel={t("pic")} emptyLabel={t("all")} value={p.queuePic} options={[{ value: "", label: `${t("pic")} · ${t("all")}` }, ...[...new Set(report.waiting.flatMap(row => row.requisitions.map(req => req.person_in_charge).filter((pic): pic is string => Boolean(pic))))].sort().map(value => ({ value, label: value }))]} onValueChange={value => patch({ queuePic: value })} /></div><div className={styles.chips}>{p.queueStage ? <button type="button" onClick={() => patch({ queueStage: "" })}>{p.queueStage}<X size={13} /></button> : null}{p.queuePic ? <button type="button" onClick={() => patch({ queuePic: "" })}>{p.queuePic}<X size={13} /></button> : null}<button type="button" onClick={() => patch({ queueStatus: "all", queueStage: "", queuePic: "", queueSearch: "" })}>{t("clear")}</button></div></> : <p className={styles.note}>{localScope}</p>}
      <div className={styles.tableScroll}><table><thead><tr>{["candidate", "position", "stage", "waiting", "due", "pic", "status", "follow"].map(key => <th key={key}>{t(key as "candidate")}</th>)}</tr></thead><tbody>{(exportMode ? visible : visible.slice(currentPage * 20, currentPage * 20 + 20)).map(row => <tr key={row.candidate.candidate_id}><td><strong>{row.candidate.name}</strong><small>{row.candidate.candidate_id}</small></td><td>{row.requisitions.map(req => <span key={req.doc_id} className={styles.positionContext}>{req.position}<small>{req.doc_id} · {req.site} · {req.department}</small></span>)}</td><td><span className={`${styles.badge} ${styles.trackBadge}`}>{stageLabel(row.instance.stage)}</span></td><td><strong className={row.status === "overdue" ? styles.bad : ""}>{fmt(row.wait)}</strong></td><td>{row.status === "unavailable" ? "—" : row.instance.due ?? "—"}</td><td>{[...new Set(row.requisitions.map(req => req.person_in_charge).filter(Boolean))].join(", ") || "—"}</td><td><span className={`${styles.badge} ${styles[row.status === "overdue" ? "overdueBadge" : row.status === "today" ? "nearBadge" : "unknownBadge"]}`}>{t(row.status)}</span></td><td><Button type="button" size="toolbar" variant="secondary" onClick={() => context.onOpenCandidate?.(row.candidate.candidate_id)}>{t("follow")} <ChevronRight size={14} /></Button></td></tr>)}</tbody></table>{!visible.length ? <p className={styles.empty}>{t("empty")}</p> : null}</div>
      {!exportMode && visible.length > 20 ? <div className={styles.pagination}><Button type="button" size="toolbar" variant="secondary" disabled={!currentPage} onClick={() => setPage(currentPage - 1)}>{t("previous")}</Button><span>{t("page")} {currentPage + 1} / {maxPage + 1}</span><Button type="button" size="toolbar" variant="secondary" disabled={currentPage === maxPage} onClick={() => setPage(currentPage + 1)}>{t("next")}</Button></div> : null}
    </section><p className={styles.note}>{t("history")}</p>
  </div>; }
  return <RiskReportFrame title={t("stageTitle")} language={language} summary={`${range.start} – ${report.asOf} · ${context.summary}`} filename={`stage-bottlenecks-${range.start}-to-${report.asOf}`} render={render} workbook={() => buildBottleneckExport(context, report, visible, localScope)} />;
}
