"use client";
import { useMemo, useRef } from "react";
import { Clock3, Flag, AlertTriangle, ChevronRight, Info, X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { CommandSelector } from "@/components/ui/CommandSelector";
import { previousPerformanceRange } from "@/lib/recruitment-performance";
import { todayDate } from "@/lib/sla";
import { buildVacancyRiskReport, riskGroups, riskGroupKey, riskRowMatches, type RiskFilter, type RiskKind, type RiskTotals } from "@/lib/vacancy-risk-report";
import { buildRiskExport } from "@/lib/risk-bottleneck-export";
import type { DashboardReportContext } from "./DashboardPortal";
import { riskCopy } from "./risk-copy";
import { Comparison, MiniTrend, RiskReportFrame } from "./RiskReportFrame";
import styles from "./risk-reports.module.css";
const categories: RiskKind[] = ["track", "near", "overdue", "unknown"];
export function RiskBar({ totals, label }: { totals: RiskTotals; label: string }) {
  return <div className={styles.riskBar} role="img" aria-label={label}>{categories.map(kind => totals[kind] ? <span key={kind} className={styles[kind]} style={{ width: `${totals[kind] / totals.open * 100}%` }} /> : null)}</div>;
}
export function VacancyRiskView({ context }: { context: DashboardReportContext }) {
  const { language, data, requisitions, preferences: p, onPreferencesChange: change, range } = context, t = riskCopy(language), actionRef = useRef<HTMLElement>(null);
  const report = useMemo(() => buildVacancyRiskReport(data, requisitions, range, todayDate(), previousPerformanceRange(p.period, { start: range.start, end: range.end < todayDate() ? range.end : todayDate() })), [data, requisitions, range, p.period]);
  const groups = riskGroups(report.rows, p.riskGrouping);
  const visible = report.rows.filter(row => riskRowMatches(row, p.riskFilter as RiskFilter) && (!p.riskGroup || riskGroupKey(row, p.riskGrouping) === p.riskGroup));
  const priority = report.rows.filter(row => riskRowMatches(row, "priority")), totals = report.totals;
  const filterScope = `${t("group")}: ${t(p.riskGrouping)} · ${t(p.riskFilter as RiskFilter)}${p.riskGroup ? ` · ${p.riskGroup}` : ""}`;
  function drill(filter: RiskFilter, group = "") { change({ riskFilter: filter, riskGroup: group }); requestAnimationFrame(() => { actionRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" }); actionRef.current?.focus(); }); }
  const format = (value: number | null) => value === null ? "—" : `${(value * 100).toFixed(1)}%`;
  function render(exportMode: boolean) { return <div className={styles.content}>
    {report.future ? <p className={styles.notice}>{t("future")}</p> : null}
    <div className={styles.riskHero}>
      <section className={styles.health}><h3>{t("health")}</h3><div className={styles.healthGrid}><div className={styles.headcountIdentity}><p aria-label={t("open")}><span>{t("openFirst")}</span><span>{t("openSecond")}</span></p><strong className={styles.bigNumber} data-risk-open>{totals.open}</strong></div><div><RiskBar totals={totals} label={categories.map(kind => `${t(kind)} ${totals[kind]}`).join(", ")} /><div className={styles.healthLegend}>{categories.filter(kind => totals[kind] || kind !== "unknown").map(kind => <div key={kind}><span className={`${styles.dot} ${styles[kind]}`} />{t(kind)}<strong>{totals[kind]}</strong></div>)}</div></div></div><p className={styles.exposure}><Info size={17} /><span><strong>{totals.near + totals.overdue}</strong> / {totals.known} {t("known")} · <strong>{format(totals.exposure)} {t("exposure")}</strong></span></p></section>
      {(["overdue", "near", "priority"] as const).map(key => { const denominator = key === "priority" ? totals.priorityOpen : totals.open; return <button key={key} type="button" className={styles.riskKpi} aria-pressed={p.riskFilter === key && !p.riskGroup} onClick={() => drill(key)}><span className={styles.kpiTop}><span className={`${styles.kpiIcon} ${key === "near" ? styles.amberSurface : styles.redSurface}`}>{key === "overdue" ? <Clock3 size={16} /> : key === "near" ? <AlertTriangle size={16} /> : <Flag size={16} />}</span><strong>{t(key)}</strong><ChevronRight size={16} /></span><b className={styles.summaryValue} data-risk-metric={key}>{totals[key]}/{denominator}</b><small className={styles.summaryContext} title={denominator ? undefined : t("noDenominator")}>({denominator ? format(totals[key] / denominator) : "—"}) {t(key === "priority" ? "ofPriority" : "ofOpen")}</small><MiniTrend values={report.trends.map(row => row[key])} label={`${t(key)}: ${report.trends.map(row => `${row.date} ${row[key]}`).join(", ")}`} tone={key === "near" ? "amber" : "red"} /><Comparison value={totals[key]} prior={report.prior?.totals[key]} range={report.priorRange} language={language} /></button>; })}
    </div>
    <div className={styles.twoColumns}>
      <section className={styles.panel}><header className={styles.sectionHead}><h3>{t("distribution")}</h3>{!exportMode ? <label className={styles.inlineField}><span>{t("group")}</span><CommandSelector typography="normal" ariaLabel={t("group")} emptyLabel={t("group")} value={p.riskGrouping} options={["department-site", "department", "site"].map(value => ({ value, label: t(value as typeof p.riskGrouping) }))} onValueChange={value => change({ riskGrouping: value as typeof p.riskGrouping, riskGroup: "" })} /></label> : null}</header><div className={styles.tableScroll}><table className={styles.distributionTable}><thead><tr><th>{t(p.riskGrouping)}</th><th>{t("distribution")}</th>{categories.filter(kind => kind !== "unknown" || totals.unknown).map(kind => <th key={kind}>{t(kind === "near" ? "approaching" : kind)}</th>)}<th>{t("total")}</th><th>{t("exposure")}</th></tr></thead><tbody>{[...groups, { name: t("total"), ...totals }].map((row, i) => <tr key={row.name} className={i === groups.length ? styles.totalRow : ""}><th>{i === groups.length ? row.name : <button type="button" onClick={() => drill("all", row.name)}>{row.name}</button>}</th><td><RiskBar totals={row} label={categories.map(kind => `${t(kind === "near" ? "approaching" : kind)} ${row[kind]}`).join(", ")} /></td>{categories.filter(kind => kind !== "unknown" || totals.unknown).map(kind => <td key={kind}>{row[kind]}</td>)}<td><strong>{row.open}</strong></td><td className={row.exposure && row.exposure > .5 ? styles.bad : ""}>{format(row.exposure)}</td></tr>)}</tbody></table></div><div className={styles.legend}>{categories.filter(kind => kind !== "unknown" || totals.unknown).map(kind => <span key={kind}><i className={`${styles.dot} ${styles[kind]}`} />{t(kind === "near" ? "approaching" : kind)}</span>)}</div></section>
      <section className={styles.panel}><header className={styles.sectionHead}><h3>{t("needs")}</h3><Button type="button" size="toolbar" variant="ghost" onClick={() => drill("priority")}>{t("viewAll")} ({priority.length})</Button></header><div className={styles.attentionList}>{priority.slice(0, 3).map(row => <div className={styles.attentionRow} key={row.requisition.doc_id}><span className={`${styles.dot} ${styles[row.kind]}`} /><div><strong>{row.requisition.position}</strong><small>{row.requisition.site} · {row.requisition.department}</small></div><span className={`${styles.badge} ${styles[row.kind + "Badge"]}`}>{row.remaining} {t("days")}</span><span className={styles.pic}>{row.requisition.person_in_charge || "—"}</span><Button type="button" size="toolbar" variant="secondary" onClick={() => context.onOpenRequisition?.(row.requisition)}>{t("review")} <ChevronRight size={14} /></Button></div>)}{!priority.length ? <p className={styles.empty}>{t("empty")}</p> : null}</div></section>
    </div>
    <section ref={exportMode ? undefined : actionRef} tabIndex={-1} className={styles.panel} aria-label={t("requisitions")}><header className={styles.sectionHead}><h3>{t("requisitions")} <small>({visible.length})</small></h3>{!exportMode ? <CommandSelector typography="normal" ariaLabel={t("risk")} emptyLabel={t("risk")} value={p.riskFilter} options={["attention", "all", "track", "near", "overdue", "unknown", "priority"].map(value => ({ value, label: t(value as RiskFilter) }))} onValueChange={value => change({ riskFilter: value })} /> : null}</header><div className={styles.chips}><span>{t(p.riskFilter as RiskFilter)}</span>{p.riskGroup ? <button type="button" onClick={() => change({ riskGroup: "" })}>{p.riskGroup}<X size={13} /></button> : null}{!exportMode ? <button type="button" onClick={() => change({ riskFilter: "all", riskGroup: "" })}>{t("clear")}</button> : null}</div><div className={styles.tableScroll}><table className={styles.riskActionTable}><thead><tr>{["position", "site", "open", "age", "remaining", "pic", "review"].map(key => <th key={key}>{t(key as "position")}</th>)}</tr></thead><tbody>{visible.map(row => <tr key={row.requisition.doc_id}><td><strong>{row.requisition.position}</strong><small>{row.requisition.doc_id} · {row.requisition.department}</small></td><td>{row.requisition.site}</td><td>{row.open}</td><td title={row.restart ? `${t("restart")} · ${row.restart}` : undefined}>{row.age === null ? "—" : `${row.age} ${t("days")}`}</td><td><span tabIndex={row.restart ? 0 : undefined} title={row.restart ? `${t("restart")} · ${row.restart}` : undefined} aria-describedby={row.restart ? exportMode ? "risk-export-restart-remark" : "risk-restart-remark" : undefined} className={`${styles.badge} ${styles[row.kind + "Badge"]}`}>{row.remaining === null ? t("unknown") : `${row.remaining} ${t("days")}`}{row.restart ? "*" : ""}</span></td><td>{row.requisition.person_in_charge || "—"}</td><td><Button type="button" size="toolbar" variant="secondary" onClick={() => context.onOpenRequisition?.(row.requisition)}>{t("review")} <ChevronRight size={14} /></Button></td></tr>)}</tbody></table>{!visible.length ? <p className={styles.empty}>{t("empty")}</p> : null}</div>{visible.some(row => row.restart) ? <p id={exportMode ? "risk-export-restart-remark" : "risk-restart-remark"} className={styles.note} data-sla-restart-remark>{t("restartRemark")}</p> : null}</section>
    <p className={styles.note}>{t("history")}</p>
  </div>; }
  return <RiskReportFrame title={t("riskTitle")} language={language} summary={`${t("asOf")} ${report.asOf} · ${context.summary}`} filename={`vacancy-risk-${report.asOf}`} render={render} workbook={() => buildRiskExport(context, report, groups, visible, filterScope)} />;
}
