begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.app_id_counters (
  entity text primary key,
  next_value integer not null default 1 check (next_value > 0)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  nickname text,
  site text,
  role text not null default 'viewer' check (role in ('system_admin', 'admin_recruiter', 'site_recruiter', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.requisitions (
  doc_id text primary key,
  pr_approved_date date,
  site text not null,
  position text not null,
  department text not null,
  section text,
  level text,
  head_count integer not null default 1 check (head_count > 0),
  person_in_charge text,
  line_manager text,
  request_type text not null default 'New' check (request_type in ('New', 'Replacement')),
  replacement_names text,
  status text not null default 'ongoing' check (status in ('ongoing', 'filled', 'cancel')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.requisition_logs (
  log_id bigint generated by default as identity primary key,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  log_date date not null,
  status text not null check (status in ('ongoing', 'filled', 'cancel')),
  remark text,
  created_at timestamptz not null default now()
);

create table if not exists public.position_groups (
  group_id text primary key,
  group_position text not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_groups (
  doc_group_id text primary key,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  group_id text references public.position_groups(group_id) on delete set null,
  group_position text not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (doc_id, group_id)
);

create table if not exists public.candidates (
  candidate_id text primary key,
  name text not null,
  phone_no text,
  doc_group_id text not null references public.document_groups(doc_group_id) on delete restrict,
  channel text,
  ref_name text,
  first_contact_date date,
  candidate_folder_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recruitment_logs (
  log_id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  log_date date not null,
  recruitment_process text not null check (
    recruitment_process in (
      'First Contact',
      'Phone Screen',
      'HR Interview',
      'Line Interview',
      'Test',
      'Reference Check',
      'Offer',
      'Rejected',
      'Withdrawn'
    )
  ),
  round integer not null default 1 check (round > 0),
  interviewer text,
  result smallint check (result in (0, 1)),
  remark text,
  created_at timestamptz not null default now()
);

create table if not exists public.offers (
  offer_id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  accepted_date date,
  first_working_date date,
  remark text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (candidate_id, doc_id)
);

create table if not exists public.sourcing_weekly_updates (
  group_id text not null references public.position_groups(group_id) on delete cascade,
  week_start date not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  channel_linkedin boolean not null default false,
  channel_walkin boolean not null default false,
  channel_referral boolean not null default false,
  channel_others boolean not null default false,
  applicants_fb integer not null default 0 check (applicants_fb >= 0),
  applicants_jobthai integer not null default 0 check (applicants_jobthai >= 0),
  applicants_jobtopgun integer not null default 0 check (applicants_jobtopgun >= 0),
  applicants_jobdb integer not null default 0 check (applicants_jobdb >= 0),
  applicants_linkedin integer not null default 0 check (applicants_linkedin >= 0),
  applicants_walkin integer not null default 0 check (applicants_walkin >= 0),
  applicants_referral integer not null default 0 check (applicants_referral >= 0),
  applicants_others integer not null default 0 check (applicants_others >= 0),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (group_id, week_start)
);

create table if not exists public.vacancy_weekly_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  week_start date not null,
  waterfall_category text not null check (waterfall_category in ('Week Start', 'Open', 'Filled', 'Total')),
  site text not null,
  request_type text not null check (request_type in ('New', 'Replacement')),
  vacancy_count integer not null default 0,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_start, waterfall_category, site, request_type)
);

create table if not exists public.change_logs (
  log_id bigint generated by default as identity primary key,
  entity text not null,
  entity_id text not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  old_data jsonb,
  new_data jsonb
);

insert into public.app_id_counters (entity, next_value)
values
  ('position_groups', 1),
  ('document_groups', 1),
  ('candidates', 1)
on conflict (entity) do nothing;

create index if not exists idx_profiles_role_site on public.profiles(role, site);
create index if not exists idx_requisitions_status_site_owner on public.requisitions(status, site, person_in_charge);
create index if not exists idx_requisitions_request_type_date on public.requisitions(request_type, pr_approved_date);
create index if not exists idx_requisition_logs_doc_date on public.requisition_logs(doc_id, log_date desc);
create index if not exists idx_position_groups_position on public.position_groups(group_position);
create index if not exists idx_document_groups_doc_id on public.document_groups(doc_id);
create index if not exists idx_document_groups_group_id on public.document_groups(group_id);
create index if not exists idx_candidates_doc_group_id on public.candidates(doc_group_id);
create index if not exists idx_recruitment_logs_candidate_latest on public.recruitment_logs(candidate_id, log_id desc);
create index if not exists idx_recruitment_logs_stage_result_date on public.recruitment_logs(recruitment_process, result, log_date desc);
create index if not exists idx_offers_candidate_id on public.offers(candidate_id);
create index if not exists idx_offers_doc_accepted on public.offers(doc_id, accepted_date) where accepted_date is not null;
create index if not exists idx_sourcing_weekly_updates_week on public.sourcing_weekly_updates(week_start);
create index if not exists idx_vacancy_weekly_snapshots_week_site on public.vacancy_weekly_snapshots(week_start, site);
create index if not exists idx_change_logs_entity on public.change_logs(entity, entity_id);
create index if not exists idx_change_logs_changed_at on public.change_logs(changed_at desc);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_requisitions_updated_at on public.requisitions;
create trigger set_requisitions_updated_at before update on public.requisitions
for each row execute function public.set_updated_at();

drop trigger if exists set_position_groups_updated_at on public.position_groups;
create trigger set_position_groups_updated_at before update on public.position_groups
for each row execute function public.set_updated_at();

drop trigger if exists set_document_groups_updated_at on public.document_groups;
create trigger set_document_groups_updated_at before update on public.document_groups
for each row execute function public.set_updated_at();

drop trigger if exists set_candidates_updated_at on public.candidates;
create trigger set_candidates_updated_at before update on public.candidates
for each row execute function public.set_updated_at();

drop trigger if exists set_offers_updated_at on public.offers;
create trigger set_offers_updated_at before update on public.offers
for each row execute function public.set_updated_at();

drop trigger if exists set_sourcing_weekly_updates_updated_at on public.sourcing_weekly_updates;
create trigger set_sourcing_weekly_updates_updated_at before update on public.sourcing_weekly_updates
for each row execute function public.set_updated_at();

drop trigger if exists set_vacancy_weekly_snapshots_updated_at on public.vacancy_weekly_snapshots;
create trigger set_vacancy_weekly_snapshots_updated_at before update on public.vacancy_weekly_snapshots
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, nickname, site, role)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(
      nullif(new.raw_user_meta_data ->> 'nickname', ''),
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      split_part(coalesce(new.email, new.id::text), '@', 1)
    ),
    nullif(new.raw_user_meta_data ->> 'site', ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'role', ''), 'viewer')
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(public.profiles.full_name, excluded.full_name),
    nickname = coalesce(public.profiles.nickname, excluded.nickname),
    site = coalesce(public.profiles.site, excluded.site),
    role = coalesce(public.profiles.role, excluded.role);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'anon')
$$;

create or replace function public.current_profile_nickname()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select nullif((select nickname from public.profiles where id = auth.uid()), '')
$$;

create or replace function public.current_profile_site()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select nullif((select site from public.profiles where id = auth.uid()), '')
$$;

create or replace function public.is_system_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() = 'system_admin'
$$;

create or replace function public.is_global_recruitment_reader()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() in ('system_admin', 'admin_recruiter', 'viewer')
$$;

create or replace function public.is_recruitment_reader()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() in ('system_admin', 'admin_recruiter', 'site_recruiter', 'viewer')
$$;

create or replace function public.is_recruitment_writer()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() in ('system_admin', 'admin_recruiter', 'site_recruiter')
$$;

create or replace function public.assert_system_admin()
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_system_admin() then
    raise exception 'System admin role is required.';
  end if;
end;
$$;

create or replace function public.assert_recruitment_writer()
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_recruitment_writer() then
    raise exception 'Recruitment write role is required.';
  end if;
end;
$$;

create or replace function public.can_read_requisition(p_doc_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_global_recruitment_reader()
    or (
      public.current_app_role() = 'site_recruiter'
      and exists (
        select 1
        from public.requisitions r
        where r.doc_id = p_doc_id
          and r.site = public.current_profile_site()
      )
    )
$$;

create or replace function public.can_manage_requisition(p_doc_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.current_app_role() in ('system_admin', 'admin_recruiter')
    or (
      public.current_app_role() = 'site_recruiter'
      and exists (
        select 1
        from public.requisitions r
        where r.doc_id = p_doc_id
          and r.site = public.current_profile_site()
          and r.person_in_charge = public.current_profile_nickname()
      )
    )
$$;

create or replace function public.can_manage_doc_group(p_doc_group_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.document_groups dg
    where dg.doc_group_id = p_doc_group_id
      and public.can_manage_requisition(dg.doc_id)
  )
$$;

create or replace function public.can_manage_candidate(p_candidate_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.candidates c
    join public.document_groups dg on dg.doc_group_id = c.doc_group_id
    where c.candidate_id = p_candidate_id
      and public.can_manage_requisition(dg.doc_id)
  )
$$;

create or replace function public.has_open_group_requisition(p_group_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.document_groups dg
    join public.requisitions r on r.doc_id = dg.doc_id
    left join lateral (
      select count(*)::integer as accepted_count
      from public.offers o
      where o.doc_id = r.doc_id
        and o.accepted_date is not null
    ) accepted on true
    where dg.group_id = p_group_id
      and r.status = 'ongoing'
      and greatest(r.head_count - coalesce(accepted.accepted_count, 0), 0) > 0
  )
$$;

create or replace function public.can_read_sourcing_group(p_group_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_global_recruitment_reader()
    or (
      public.current_app_role() = 'site_recruiter'
      and exists (
        select 1
        from public.document_groups dg
        join public.requisitions r on r.doc_id = dg.doc_id
        where dg.group_id = p_group_id
          and r.person_in_charge = public.current_profile_nickname()
      )
    )
$$;

create or replace function public.can_manage_sourcing_group(p_group_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.current_app_role() in ('system_admin', 'admin_recruiter')
    or (
      public.current_app_role() = 'site_recruiter'
      and exists (
        select 1
        from public.document_groups dg
        join public.requisitions r on r.doc_id = dg.doc_id
        left join lateral (
          select count(*)::integer as accepted_count
          from public.offers o
          where o.doc_id = r.doc_id
            and o.accepted_date is not null
        ) accepted on true
        where dg.group_id = p_group_id
          and r.status = 'ongoing'
          and r.person_in_charge = public.current_profile_nickname()
          and greatest(r.head_count - coalesce(accepted.accepted_count, 0), 0) > 0
      )
    )
$$;

create or replace function public.next_app_id(p_entity text, p_prefix text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_value integer;
begin
  if p_entity is null or p_prefix is null then
    raise exception 'Entity and prefix are required.';
  end if;

  insert into public.app_id_counters (entity, next_value)
  values (p_entity, 1)
  on conflict (entity) do nothing;

  update public.app_id_counters
  set next_value = next_value + 1
  where entity = p_entity
  returning next_value - 1 into v_value;

  return p_prefix || '-' || lpad(v_value::text, 4, '0');
end;
$$;

create or replace function public.next_prefixed_id(p_table text, p_column text, p_prefix text)
returns text
language sql
security definer
set search_path = public
as $$
  select public.next_app_id(p_table, p_prefix)
$$;

create or replace function public.refresh_requisition_status(p_doc_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_head_count integer;
  v_status text;
  v_accepted_count integer;
  v_next_status text;
begin
  select head_count, status into v_head_count, v_status
  from public.requisitions
  where doc_id = p_doc_id;

  if not found or v_status = 'cancel' then
    return;
  end if;

  select count(*) into v_accepted_count
  from public.offers
  where doc_id = p_doc_id
    and accepted_date is not null;

  v_next_status := case when v_accepted_count >= v_head_count then 'filled' else 'ongoing' end;

  if v_next_status <> v_status then
    update public.requisitions
    set status = v_next_status
    where doc_id = p_doc_id;
  end if;
end;
$$;

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_action text;
  v_entity_id text;
  v_email text;
begin
  v_row := coalesce(to_jsonb(new), to_jsonb(old));
  v_entity_id := coalesce(
    v_row ->> 'doc_id',
    v_row ->> 'candidate_id',
    v_row ->> 'group_id',
    v_row ->> 'doc_group_id',
    v_row ->> 'offer_id',
    v_row ->> 'snapshot_id',
    v_row ->> 'log_id',
    v_row ->> 'week_start',
    'unknown'
  );
  v_action := coalesce(nullif(current_setting('app.action', true), ''), lower(tg_op));
  v_email := coalesce(
    (select email from public.profiles where id = auth.uid()),
    auth.jwt() ->> 'email'
  );

  insert into public.change_logs (entity, entity_id, action, changed_by, changed_by_email, old_data, new_data)
  values (
    tg_table_name,
    v_entity_id,
    v_action,
    auth.uid(),
    v_email,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists audit_requisitions on public.requisitions;
create trigger audit_requisitions after insert or update or delete on public.requisitions
for each row execute function public.audit_row_change();

drop trigger if exists audit_requisition_logs on public.requisition_logs;
create trigger audit_requisition_logs after insert or update or delete on public.requisition_logs
for each row execute function public.audit_row_change();

drop trigger if exists audit_position_groups on public.position_groups;
create trigger audit_position_groups after insert or update or delete on public.position_groups
for each row execute function public.audit_row_change();

drop trigger if exists audit_document_groups on public.document_groups;
create trigger audit_document_groups after insert or update or delete on public.document_groups
for each row execute function public.audit_row_change();

drop trigger if exists audit_candidates on public.candidates;
create trigger audit_candidates after insert or update or delete on public.candidates
for each row execute function public.audit_row_change();

drop trigger if exists audit_recruitment_logs on public.recruitment_logs;
create trigger audit_recruitment_logs after insert or update or delete on public.recruitment_logs
for each row execute function public.audit_row_change();

drop trigger if exists audit_offers on public.offers;
create trigger audit_offers after insert or update or delete on public.offers
for each row execute function public.audit_row_change();

drop trigger if exists audit_sourcing_weekly_updates on public.sourcing_weekly_updates;
create trigger audit_sourcing_weekly_updates after insert or update or delete on public.sourcing_weekly_updates
for each row execute function public.audit_row_change();

drop trigger if exists audit_vacancy_weekly_snapshots on public.vacancy_weekly_snapshots;
create trigger audit_vacancy_weekly_snapshots after insert or update or delete on public.vacancy_weekly_snapshots
for each row execute function public.audit_row_change();

alter table public.profiles enable row level security;
alter table public.requisitions enable row level security;
alter table public.requisition_logs enable row level security;
alter table public.position_groups enable row level security;
alter table public.document_groups enable row level security;
alter table public.candidates enable row level security;
alter table public.recruitment_logs enable row level security;
alter table public.offers enable row level security;
alter table public.sourcing_weekly_updates enable row level security;
alter table public.vacancy_weekly_snapshots enable row level security;
alter table public.change_logs enable row level security;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_system_admin());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.is_system_admin())
with check (public.is_system_admin());

drop policy if exists requisitions_read on public.requisitions;
create policy requisitions_read on public.requisitions
for select to authenticated
using (
  public.is_global_recruitment_reader()
  or (
    public.current_app_role() = 'site_recruiter'
    and site = public.current_profile_site()
  )
);

drop policy if exists requisition_logs_read on public.requisition_logs;
create policy requisition_logs_read on public.requisition_logs
for select to authenticated
using (public.can_read_requisition(doc_id));

drop policy if exists position_groups_read on public.position_groups;
create policy position_groups_read on public.position_groups
for select to authenticated
using (public.is_recruitment_reader());

drop policy if exists document_groups_read on public.document_groups;
create policy document_groups_read on public.document_groups
for select to authenticated
using (public.can_read_requisition(doc_id));

drop policy if exists candidates_read on public.candidates;
create policy candidates_read on public.candidates
for select to authenticated
using (
  exists (
    select 1
    from public.document_groups dg
    where dg.doc_group_id = candidates.doc_group_id
      and public.can_read_requisition(dg.doc_id)
  )
);

drop policy if exists recruitment_logs_read on public.recruitment_logs;
create policy recruitment_logs_read on public.recruitment_logs
for select to authenticated
using (
  exists (
    select 1
    from public.candidates c
    join public.document_groups dg on dg.doc_group_id = c.doc_group_id
    where c.candidate_id = recruitment_logs.candidate_id
      and public.can_read_requisition(dg.doc_id)
  )
);

drop policy if exists offers_read on public.offers;
create policy offers_read on public.offers
for select to authenticated
using (public.can_read_requisition(doc_id));

drop policy if exists sourcing_weekly_updates_read on public.sourcing_weekly_updates;
create policy sourcing_weekly_updates_read on public.sourcing_weekly_updates
for select to authenticated
using (public.can_read_sourcing_group(group_id));

drop policy if exists vacancy_weekly_snapshots_read on public.vacancy_weekly_snapshots;
create policy vacancy_weekly_snapshots_read on public.vacancy_weekly_snapshots
for select to authenticated
using (
  public.is_global_recruitment_reader()
  or (
    public.current_app_role() = 'site_recruiter'
    and site = public.current_profile_site()
  )
);

drop policy if exists change_logs_read on public.change_logs;
create policy change_logs_read on public.change_logs
for select to authenticated
using (public.is_global_recruitment_reader());

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select on public.requisitions to authenticated;
grant select on public.requisition_logs to authenticated;
grant select on public.position_groups to authenticated;
grant select on public.document_groups to authenticated;
grant select on public.candidates to authenticated;
grant select on public.recruitment_logs to authenticated;
grant select on public.offers to authenticated;
grant select on public.sourcing_weekly_updates to authenticated;
grant select on public.vacancy_weekly_snapshots to authenticated;
grant select on public.change_logs to authenticated;

create or replace function public.app_upsert_requisition(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text := coalesce(payload ->> 'mode', 'new');
  v_doc_id text := nullif(payload ->> 'doc_id', '');
  v_exists boolean;
  v_status text := coalesce(nullif(payload ->> 'status', ''), 'ongoing');
  v_role text := public.current_app_role();
  v_site text := nullif(payload ->> 'site', '');
  v_person_in_charge text := nullif(payload ->> 'person_in_charge', '');
  v_request_type text := coalesce(nullif(payload ->> 'request_type', ''), 'New');
  v_replacement_names text := nullif(payload ->> 'replacement_names', '');
begin
  perform public.assert_recruitment_writer();
  if v_doc_id is null then raise exception 'Doc ID is required.'; end if;
  if v_mode not in ('new', 'change') then raise exception 'mode must be new or change'; end if;
  if v_status not in ('ongoing', 'cancel') then raise exception 'Requisition status can only be ongoing or cancel. Filled is automatic.'; end if;
  if v_request_type not in ('New', 'Replacement') then raise exception 'Request type must be New or Replacement.'; end if;
  if v_request_type = 'Replacement' and v_replacement_names is null then raise exception 'Replacement names are required for replacement requisitions.'; end if;
  if v_request_type = 'New' then v_replacement_names := null; end if;

  if v_role = 'site_recruiter' then
    v_site := public.current_profile_site();
    v_person_in_charge := public.current_profile_nickname();
    if v_site is null or v_person_in_charge is null then
      raise exception 'Site recruiter accounts require assigned site and nickname.';
    end if;
  end if;

  select exists(select 1 from public.requisitions where doc_id = v_doc_id) into v_exists;
  if v_mode = 'new' and v_exists then raise exception 'Requisition Doc ID already exists. Switch to Change mode to edit it.'; end if;
  if v_mode = 'change' and not v_exists then raise exception 'Requisition Doc ID does not exist. Switch to New mode to create it.'; end if;
  if v_mode = 'change' and not public.can_manage_requisition(v_doc_id) then raise exception 'You can edit only requisitions where you are person in charge.'; end if;

  perform set_config('app.action', 'requisition:' || v_mode, true);

  insert into public.requisitions (
    doc_id, pr_approved_date, site, position, department, section, level,
    head_count, person_in_charge, line_manager, request_type, replacement_names, status
  )
  values (
    v_doc_id,
    nullif(payload ->> 'pr_approved_date', '')::date,
    v_site,
    nullif(payload ->> 'position', ''),
    nullif(payload ->> 'department', ''),
    nullif(payload ->> 'section', ''),
    nullif(payload ->> 'level', ''),
    coalesce(nullif(payload ->> 'head_count', '')::integer, 1),
    v_person_in_charge,
    nullif(payload ->> 'line_manager', ''),
    v_request_type,
    v_replacement_names,
    v_status
  )
  on conflict (doc_id) do update set
    pr_approved_date = excluded.pr_approved_date,
    site = excluded.site,
    position = excluded.position,
    department = excluded.department,
    section = excluded.section,
    level = excluded.level,
    head_count = excluded.head_count,
    person_in_charge = excluded.person_in_charge,
    line_manager = excluded.line_manager,
    request_type = excluded.request_type,
    replacement_names = excluded.replacement_names,
    status = excluded.status;

  perform set_config('app.action', 'auto-status', true);
  perform public.refresh_requisition_status(v_doc_id);
  return jsonb_build_object('ok', true, 'id', v_doc_id);
end;
$$;

create or replace function public.app_insert_requisition_log(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doc_id text := nullif(payload ->> 'doc_id', '');
  v_status text := nullif(payload ->> 'status', '');
begin
  perform public.assert_recruitment_writer();
  if not public.can_manage_requisition(v_doc_id) then raise exception 'You can update status only for requisitions where you are person in charge.'; end if;
  if v_status not in ('ongoing', 'filled', 'cancel') then raise exception 'Status must be ongoing, filled, or cancel.'; end if;

  perform set_config('app.action', 'requisition:status', true);
  insert into public.requisition_logs (doc_id, log_date, status, remark)
  values (v_doc_id, nullif(payload ->> 'log_date', '')::date, v_status, nullif(payload ->> 'remark', ''));

  update public.requisitions set status = v_status where doc_id = v_doc_id;
  perform set_config('app.action', 'auto-status', true);
  perform public.refresh_requisition_status(v_doc_id);
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.app_upsert_position_group(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text := coalesce(payload ->> 'mode', 'new');
  v_group_id text := nullif(payload ->> 'group_id', '');
  v_exists boolean;
begin
  perform public.assert_recruitment_writer();
  if v_mode not in ('new', 'change') then
    raise exception 'mode must be new or change';
  end if;
  if v_mode = 'new' then
    v_group_id := public.next_app_id('position_groups', 'GRP');
  elsif v_group_id is null then
    raise exception 'Group ID is required in Change mode.';
  end if;

  select exists(select 1 from public.position_groups where group_id = v_group_id) into v_exists;
  if v_mode = 'new' and v_exists then raise exception 'Group ID already exists. Switch to Change mode to edit it.'; end if;
  if v_mode = 'change' and not v_exists then raise exception 'Group ID does not exist. Switch to New mode to create it.'; end if;
  if v_mode = 'change' and not public.can_manage_sourcing_group(v_group_id) then
    raise exception 'You can edit only sourcing groups linked to requisitions where you are responsible.';
  end if;

  perform set_config('app.action', 'position_group:' || v_mode, true);
  insert into public.position_groups (
    group_id, group_position,
    channel_fb, channel_jobthai, channel_jobtopgun, channel_jobdb,
    channel_linkedin, channel_walkin, channel_referral, channel_others
  )
  values (
    v_group_id,
    nullif(payload ->> 'group_position', ''),
    coalesce((payload ->> 'channel_fb')::boolean, false),
    coalesce((payload ->> 'channel_jobthai')::boolean, false),
    coalesce((payload ->> 'channel_jobtopgun')::boolean, false),
    coalesce((payload ->> 'channel_jobdb')::boolean, false),
    coalesce((payload ->> 'channel_linkedin')::boolean, false),
    coalesce((payload ->> 'channel_walkin')::boolean, false),
    coalesce((payload ->> 'channel_referral')::boolean, false),
    coalesce((payload ->> 'channel_others')::boolean, false)
  )
  on conflict (group_id) do update set
    group_position = excluded.group_position,
    channel_fb = excluded.channel_fb,
    channel_jobthai = excluded.channel_jobthai,
    channel_jobtopgun = excluded.channel_jobtopgun,
    channel_jobdb = excluded.channel_jobdb,
    channel_linkedin = excluded.channel_linkedin,
    channel_walkin = excluded.channel_walkin,
    channel_referral = excluded.channel_referral,
    channel_others = excluded.channel_others;

  return jsonb_build_object('ok', true, 'id', v_group_id);
end;
$$;

create or replace function public.app_create_group_match(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doc_id text := nullif(payload ->> 'doc_id', '');
  v_group_id text := nullif(payload ->> 'group_id', '');
  v_doc_group_id text;
  v_group public.position_groups%rowtype;
begin
  perform public.assert_recruitment_writer();
  if v_doc_id is null or not exists(select 1 from public.requisitions where doc_id = v_doc_id) then
    raise exception 'Requisition does not exist.';
  end if;
  if not public.can_manage_requisition(v_doc_id) then
    raise exception 'You can match only requisitions where you are person in charge.';
  end if;
  select * into v_group from public.position_groups where group_id = v_group_id;
  if not found then raise exception 'Group ID does not exist.'; end if;
  if exists(select 1 from public.document_groups where doc_id = v_doc_id) then
    raise exception 'This requisition is already matched.';
  end if;

  v_doc_group_id := public.next_app_id('document_groups', 'DGRP');
  perform set_config('app.action', 'document_group:new', true);
  insert into public.document_groups (
    doc_group_id, doc_id, group_id, group_position,
    channel_fb, channel_jobthai, channel_jobtopgun, channel_jobdb,
    channel_linkedin, channel_walkin, channel_referral, channel_others
  )
  values (
    v_doc_group_id, v_doc_id, v_group_id, v_group.group_position,
    v_group.channel_fb, v_group.channel_jobthai, v_group.channel_jobtopgun, v_group.channel_jobdb,
    v_group.channel_linkedin, v_group.channel_walkin, v_group.channel_referral, v_group.channel_others
  );

  return jsonb_build_object('ok', true, 'id', v_doc_group_id);
end;
$$;

create or replace function public.app_upsert_sourcing_weekly_update(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_group_id text := nullif(payload ->> 'group_id', '');
  v_week_start date := nullif(payload ->> 'week_start', '')::date;
  v_group public.position_groups%rowtype;
begin
  perform public.assert_recruitment_writer();
  if v_group_id is null then raise exception 'Group ID is required.'; end if;
  if v_week_start is null then raise exception 'Week start is required.'; end if;
  if not public.has_open_group_requisition(v_group_id) then raise exception 'Group has no unfilled active requisition.'; end if;
  if not public.can_manage_sourcing_group(v_group_id) then raise exception 'You can update only sourcing groups where you are responsible.'; end if;
  select * into v_group from public.position_groups where group_id = v_group_id;

  perform set_config('app.action', 'sourcing_update:upsert', true);
  insert into public.sourcing_weekly_updates (
    group_id, week_start,
    channel_fb, channel_jobthai, channel_jobtopgun, channel_jobdb,
    channel_linkedin, channel_walkin, channel_referral, channel_others,
    applicants_fb, applicants_jobthai, applicants_jobtopgun, applicants_jobdb,
    applicants_linkedin, applicants_walkin, applicants_referral, applicants_others,
    updated_by
  )
  values (
    v_group_id,
    v_week_start,
    case when payload ? 'channel_fb' then (payload ->> 'channel_fb')::boolean else coalesce(v_group.channel_fb, false) end,
    case when payload ? 'channel_jobthai' then (payload ->> 'channel_jobthai')::boolean else coalesce(v_group.channel_jobthai, false) end,
    case when payload ? 'channel_jobtopgun' then (payload ->> 'channel_jobtopgun')::boolean else coalesce(v_group.channel_jobtopgun, false) end,
    case when payload ? 'channel_jobdb' then (payload ->> 'channel_jobdb')::boolean else coalesce(v_group.channel_jobdb, false) end,
    case when payload ? 'channel_linkedin' then (payload ->> 'channel_linkedin')::boolean else coalesce(v_group.channel_linkedin, false) end,
    case when payload ? 'channel_walkin' then (payload ->> 'channel_walkin')::boolean else coalesce(v_group.channel_walkin, false) end,
    case when payload ? 'channel_referral' then (payload ->> 'channel_referral')::boolean else coalesce(v_group.channel_referral, false) end,
    case when payload ? 'channel_others' then (payload ->> 'channel_others')::boolean else coalesce(v_group.channel_others, false) end,
    coalesce(nullif(payload ->> 'applicants_fb', '')::integer, 0),
    coalesce(nullif(payload ->> 'applicants_jobthai', '')::integer, 0),
    coalesce(nullif(payload ->> 'applicants_jobtopgun', '')::integer, 0),
    coalesce(nullif(payload ->> 'applicants_jobdb', '')::integer, 0),
    coalesce(nullif(payload ->> 'applicants_linkedin', '')::integer, 0),
    coalesce(nullif(payload ->> 'applicants_walkin', '')::integer, 0),
    coalesce(nullif(payload ->> 'applicants_referral', '')::integer, 0),
    coalesce(nullif(payload ->> 'applicants_others', '')::integer, 0),
    auth.uid()
  )
  on conflict (group_id, week_start) do update set
    channel_fb = case when payload ? 'channel_fb' then excluded.channel_fb else sourcing_weekly_updates.channel_fb end,
    channel_jobthai = case when payload ? 'channel_jobthai' then excluded.channel_jobthai else sourcing_weekly_updates.channel_jobthai end,
    channel_jobtopgun = case when payload ? 'channel_jobtopgun' then excluded.channel_jobtopgun else sourcing_weekly_updates.channel_jobtopgun end,
    channel_jobdb = case when payload ? 'channel_jobdb' then excluded.channel_jobdb else sourcing_weekly_updates.channel_jobdb end,
    channel_linkedin = case when payload ? 'channel_linkedin' then excluded.channel_linkedin else sourcing_weekly_updates.channel_linkedin end,
    channel_walkin = case when payload ? 'channel_walkin' then excluded.channel_walkin else sourcing_weekly_updates.channel_walkin end,
    channel_referral = case when payload ? 'channel_referral' then excluded.channel_referral else sourcing_weekly_updates.channel_referral end,
    channel_others = case when payload ? 'channel_others' then excluded.channel_others else sourcing_weekly_updates.channel_others end,
    applicants_fb = excluded.applicants_fb,
    applicants_jobthai = excluded.applicants_jobthai,
    applicants_jobtopgun = excluded.applicants_jobtopgun,
    applicants_jobdb = excluded.applicants_jobdb,
    applicants_linkedin = excluded.applicants_linkedin,
    applicants_walkin = excluded.applicants_walkin,
    applicants_referral = excluded.applicants_referral,
    applicants_others = excluded.applicants_others,
    updated_by = excluded.updated_by;

  return jsonb_build_object('ok', true, 'id', v_group_id);
end;
$$;

create or replace function public.app_upsert_candidate(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text := coalesce(payload ->> 'mode', 'new');
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_doc_group_id text := nullif(payload ->> 'doc_group_id', '');
  v_exists boolean;
  v_initial_log_date date;
begin
  perform public.assert_recruitment_writer();
  if not public.can_manage_doc_group(v_doc_group_id) then raise exception 'You can create candidates only for requisitions where you are person in charge.'; end if;

  if v_mode = 'new' then
    v_candidate_id := public.next_app_id('candidates', 'CAN');
  elsif v_candidate_id is null then
    raise exception 'Candidate ID is required in Change mode.';
  end if;

  select exists(select 1 from public.candidates where candidate_id = v_candidate_id) into v_exists;
  if v_mode = 'new' and v_exists then raise exception 'Candidate ID already exists. Switch to Change mode to edit it.'; end if;
  if v_mode = 'change' and not v_exists then raise exception 'Candidate ID does not exist. Switch to New mode to create it.'; end if;
  if v_mode = 'change' and not public.can_manage_candidate(v_candidate_id) then raise exception 'You can edit candidates only for requisitions where you are person in charge.'; end if;

  perform set_config('app.action', 'candidate:' || v_mode, true);
  insert into public.candidates (candidate_id, name, phone_no, doc_group_id, channel, ref_name, first_contact_date, candidate_folder_url)
  values (
    v_candidate_id,
    nullif(payload ->> 'name', ''),
    nullif(payload ->> 'phone_no', ''),
    v_doc_group_id,
    nullif(payload ->> 'channel', ''),
    nullif(payload ->> 'ref_name', ''),
    nullif(payload ->> 'first_contact_date', '')::date,
    nullif(payload ->> 'candidate_folder_url', '')
  )
  on conflict (candidate_id) do update set
    name = excluded.name,
    phone_no = excluded.phone_no,
    doc_group_id = excluded.doc_group_id,
    channel = excluded.channel,
    ref_name = excluded.ref_name,
    first_contact_date = excluded.first_contact_date,
    candidate_folder_url = excluded.candidate_folder_url;

  if v_mode = 'new' then
    v_initial_log_date := coalesce(nullif(payload ->> 'first_contact_date', '')::date, current_date);
    perform set_config('app.action', 'recruitment_log:auto-phone-screen', true);
    insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
    values (v_candidate_id, v_initial_log_date, 'Phone Screen', 1, null, null, 'Initial pending phone screening');
  end if;

  return jsonb_build_object('ok', true, 'id', v_candidate_id);
end;
$$;

create or replace function public.app_insert_recruitment_log(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_stage text := nullif(payload ->> 'recruitment_process', '');
  v_result smallint := nullif(payload ->> 'result', '')::smallint;
  v_source text := coalesce(nullif(payload ->> 'source', ''), 'manual');
  v_current_stage text;
  v_current_result smallint;
  v_current_index integer;
  v_next_index integer;
  v_log_id bigint;
  v_stages text[] := array[
    'First Contact', 'Phone Screen', 'HR Interview', 'Line Interview', 'Test',
    'Reference Check', 'Offer', 'Rejected', 'Withdrawn'
  ];
  v_active_stages text[] := array[
    'Phone Screen', 'HR Interview', 'Line Interview', 'Test', 'Reference Check', 'Offer'
  ];
  v_auto_next_stage text;
begin
  perform public.assert_recruitment_writer();
  if not public.can_manage_candidate(v_candidate_id) then raise exception 'You can update process only for candidates where you are person in charge.'; end if;

  select recruitment_process, result
    into v_current_stage, v_current_result
  from public.recruitment_logs
  where candidate_id = v_candidate_id
  order by log_id desc
  limit 1;

  if v_source = 'pipeline' then
    v_current_index := coalesce(array_position(v_stages, v_current_stage), 0);
    v_next_index := coalesce(array_position(v_stages, v_stage), 0);

    if v_next_index <= v_current_index then
      raise exception 'Pipeline cards can move forward only.';
    end if;
  end if;

  perform set_config('app.action', 'recruitment_log:new', true);
  insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
  values (
    v_candidate_id,
    nullif(payload ->> 'log_date', '')::date,
    v_stage,
    coalesce(nullif(payload ->> 'round', '')::integer, 1),
    nullif(payload ->> 'interviewer', ''),
    v_result,
    nullif(payload ->> 'remark', '')
  )
  returning log_id into v_log_id;

  if v_result = 1
    and v_current_stage = v_stage
    and v_current_result is null
    and array_position(v_active_stages, v_stage) is not null
    and array_position(v_active_stages, v_stage) < array_length(v_active_stages, 1)
  then
    v_auto_next_stage := v_active_stages[array_position(v_active_stages, v_stage) + 1];
    perform set_config('app.action', 'recruitment_log:auto-next-pending', true);
    insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
    values (
      v_candidate_id,
      nullif(payload ->> 'log_date', '')::date,
      v_auto_next_stage,
      1,
      null,
      null,
      'Auto-progressed after pass'
    );
  end if;

  update public.candidates set updated_at = now() where candidate_id = v_candidate_id;
  return jsonb_build_object('ok', true, 'id', v_log_id::text);
end;
$$;

create or replace function public.app_insert_pipeline_passes(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_target_stage text := nullif(payload ->> 'target_stage', '');
  v_stages jsonb := coalesce(payload -> 'stages', '[]'::jsonb);
  v_current_stage text;
  v_current_result smallint;
  v_current_index integer;
  v_target_index integer;
  v_stage_count integer := jsonb_array_length(v_stages);
  v_active_stages text[] := array[
    'Phone Screen', 'HR Interview', 'Line Interview', 'Test', 'Reference Check', 'Offer'
  ];
  v_item jsonb;
  v_expected_stage text;
  v_log_id bigint;
begin
  perform public.assert_recruitment_writer();
  if v_candidate_id is null then raise exception 'Candidate is required.'; end if;
  if v_target_stage is null then raise exception 'Target stage is required.'; end if;
  if v_stage_count = 0 then raise exception 'At least one passed stage is required.'; end if;
  if not public.can_manage_candidate(v_candidate_id) then raise exception 'You can update process only for candidates where you are person in charge.'; end if;

  select recruitment_process, result
    into v_current_stage, v_current_result
  from public.recruitment_logs
  where candidate_id = v_candidate_id
  order by log_id desc
  limit 1;

  v_current_index := coalesce(array_position(v_active_stages, v_current_stage), 0);
  v_target_index := coalesce(array_position(v_active_stages, v_target_stage), 0);

  if v_current_index = 0 then raise exception 'Candidate is not in an active pipeline stage.'; end if;
  if v_current_result is not null then raise exception 'Latest candidate stage is already completed.'; end if;
  if v_target_index <= v_current_index then raise exception 'Pipeline cards can move forward only.'; end if;
  if v_target_index <> v_current_index + v_stage_count then
    raise exception 'All passed stages between current and target must be confirmed.';
  end if;

  for v_item in select value from jsonb_array_elements(v_stages)
  loop
    v_expected_stage := v_active_stages[v_current_index + coalesce((v_item ->> 'index')::integer, 0)];
    if nullif(v_item ->> 'stage', '') <> v_expected_stage then
      raise exception 'Passed stages must be consecutive from the current stage.';
    end if;
  end loop;

  perform set_config('app.action', 'recruitment_log:pipeline-pass', true);
  for v_item in select value from jsonb_array_elements(v_stages)
  loop
    insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
    values (
      v_candidate_id,
      nullif(v_item ->> 'log_date', '')::date,
      nullif(v_item ->> 'stage', ''),
      coalesce(nullif(v_item ->> 'round', '')::integer, 1),
      nullif(v_item ->> 'interviewer', ''),
      1,
      nullif(v_item ->> 'remark', '')
    )
    returning log_id into v_log_id;
  end loop;

  perform set_config('app.action', 'recruitment_log:auto-next-pending', true);
  insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
  values (
    v_candidate_id,
    coalesce(nullif((v_stages -> (v_stage_count - 1)) ->> 'log_date', '')::date, current_date),
    v_target_stage,
    1,
    null,
    null,
    'Auto-created pending stage after pipeline drag and drop'
  );

  update public.candidates set updated_at = now() where candidate_id = v_candidate_id;
  return jsonb_build_object('ok', true, 'id', v_log_id::text);
end;
$$;

create or replace function public.app_insert_test_maintenance(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_current_test jsonb := coalesce(payload -> 'current_test', '{}'::jsonb);
  v_next_test jsonb := coalesce(payload -> 'next_test', '{}'::jsonb);
  v_current_stage text;
  v_current_result smallint;
  v_latest_round integer;
  v_current_round integer := coalesce(nullif(v_current_test ->> 'round', '')::integer, 1);
  v_next_round integer := coalesce(nullif(v_next_test ->> 'round', '')::integer, v_current_round + 1);
  v_log_id bigint;
begin
  perform public.assert_recruitment_writer();
  if v_candidate_id is null then raise exception 'Candidate is required.'; end if;
  if not public.can_manage_candidate(v_candidate_id) then raise exception 'You can update process only for candidates where you are person in charge.'; end if;

  select recruitment_process, result, round
    into v_current_stage, v_current_result, v_latest_round
  from public.recruitment_logs
  where candidate_id = v_candidate_id
  order by log_id desc
  limit 1;

  if v_current_stage <> 'Test' or v_current_result is not null then
    raise exception 'Candidate must be in a pending Test round.';
  end if;
  if v_current_round <> v_latest_round then
    raise exception 'Current Test round does not match the latest pending Test round.';
  end if;
  if v_next_round <= v_current_round then
    raise exception 'Next Test round must be greater than the current round.';
  end if;

  perform set_config('app.action', 'recruitment_log:test-current-pass', true);
  insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
  values (
    v_candidate_id,
    nullif(v_current_test ->> 'log_date', '')::date,
    'Test',
    v_current_round,
    nullif(v_current_test ->> 'interviewer', ''),
    1,
    nullif(v_current_test ->> 'remark', '')
  )
  returning log_id into v_log_id;

  perform set_config('app.action', 'recruitment_log:test-next-pending', true);
  insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
  values (
    v_candidate_id,
    nullif(v_next_test ->> 'log_date', '')::date,
    'Test',
    v_next_round,
    nullif(v_next_test ->> 'interviewer', ''),
    null,
    nullif(v_next_test ->> 'remark', '')
  )
  returning log_id into v_log_id;

  update public.candidates set updated_at = now() where candidate_id = v_candidate_id;
  return jsonb_build_object('ok', true, 'id', v_log_id::text);
end;
$$;

create or replace function public.app_insert_pipeline_test_exit(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_target_stage text := nullif(payload ->> 'target_stage', '');
  v_stages jsonb := coalesce(payload -> 'stages', '[]'::jsonb);
  v_extra_rounds jsonb := coalesce(payload -> 'extra_test_rounds', '[]'::jsonb);
  v_stage_count integer := jsonb_array_length(v_stages);
  v_current_stage text;
  v_current_result smallint;
  v_latest_round integer;
  v_pass_stage jsonb;
  v_pass_round integer;
  v_item jsonb;
  v_log_id bigint;
begin
  perform public.assert_recruitment_writer();
  if v_candidate_id is null then raise exception 'Candidate is required.'; end if;
  if v_target_stage <> 'Reference Check' then raise exception 'Test exit target must be Reference Check.'; end if;
  if v_stage_count <> 1 then raise exception 'Test exit must pass exactly one Test stage.'; end if;
  if not public.can_manage_candidate(v_candidate_id) then raise exception 'You can update process only for candidates where you are person in charge.'; end if;

  select recruitment_process, result, round
    into v_current_stage, v_current_result, v_latest_round
  from public.recruitment_logs
  where candidate_id = v_candidate_id
  order by log_id desc
  limit 1;

  if v_current_stage <> 'Test' or v_current_result is not null then
    raise exception 'Candidate must be in a pending Test round.';
  end if;

  v_pass_stage := v_stages -> 0;
  if nullif(v_pass_stage ->> 'stage', '') <> 'Test' then
    raise exception 'Test exit must pass the Test stage.';
  end if;
  v_pass_round := coalesce(nullif(v_pass_stage ->> 'round', '')::integer, 1);
  if v_pass_round <> v_latest_round then
    raise exception 'Test exit pass round must match the latest pending Test round.';
  end if;

  perform set_config('app.action', 'recruitment_log:test-extra-pending', true);
  for v_item in select value from jsonb_array_elements(v_extra_rounds)
  loop
    if coalesce(nullif(v_item ->> 'round', '')::integer, 0) <= v_pass_round then
      raise exception 'Additional Test rounds must be greater than the pass round.';
    end if;
    insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
    values (
      v_candidate_id,
      nullif(v_item ->> 'log_date', '')::date,
      'Test',
      coalesce(nullif(v_item ->> 'round', '')::integer, v_pass_round + 1),
      nullif(v_item ->> 'interviewer', ''),
      null,
      nullif(v_item ->> 'remark', '')
    )
    returning log_id into v_log_id;
  end loop;

  perform set_config('app.action', 'recruitment_log:test-pass', true);
  insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
  values (
    v_candidate_id,
    nullif(v_pass_stage ->> 'log_date', '')::date,
    'Test',
    v_pass_round,
    nullif(v_pass_stage ->> 'interviewer', ''),
    1,
    nullif(v_pass_stage ->> 'remark', '')
  )
  returning log_id into v_log_id;

  perform set_config('app.action', 'recruitment_log:auto-next-pending', true);
  insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
  values (
    v_candidate_id,
    coalesce(nullif(v_pass_stage ->> 'log_date', '')::date, current_date),
    'Reference Check',
    1,
    null,
    null,
    'Auto-created pending stage after Test exit'
  );

  update public.candidates set updated_at = now() where candidate_id = v_candidate_id;
  return jsonb_build_object('ok', true, 'id', v_log_id::text);
end;
$$;

create or replace function public.app_upsert_offer(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text := coalesce(payload ->> 'mode', 'new');
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_doc_id text := nullif(payload ->> 'doc_id', '');
  v_exists boolean;
  v_offer_id bigint;
begin
  perform public.assert_recruitment_writer();
  if not public.can_manage_requisition(v_doc_id) or not public.can_manage_candidate(v_candidate_id) then
    raise exception 'You can create offers only for requisitions where you are person in charge.';
  end if;

  select exists(select 1 from public.offers where candidate_id = v_candidate_id and doc_id = v_doc_id) into v_exists;
  if v_mode = 'new' and v_exists then raise exception 'This offer already exists. Switch to Change mode to edit it.'; end if;
  if v_mode = 'change' and not v_exists then raise exception 'This offer does not exist. Switch to New mode to create it.'; end if;

  perform set_config('app.action', 'offer:' || v_mode, true);
  insert into public.offers (candidate_id, doc_id, accepted_date, first_working_date, remark)
  values (
    v_candidate_id,
    v_doc_id,
    nullif(payload ->> 'accepted_date', '')::date,
    nullif(payload ->> 'first_working_date', '')::date,
    nullif(payload ->> 'remark', '')
  )
  on conflict (candidate_id, doc_id) do update set
    accepted_date = excluded.accepted_date,
    first_working_date = excluded.first_working_date,
    remark = excluded.remark
  returning offer_id into v_offer_id;

  perform set_config('app.action', 'auto-status', true);
  perform public.refresh_requisition_status(v_doc_id);
  return jsonb_build_object('ok', true, 'id', v_offer_id::text);
end;
$$;

create or replace function public.app_upsert_vacancy_weekly_snapshot(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week_start date := nullif(payload ->> 'week_start', '')::date;
  v_category text := nullif(payload ->> 'waterfall_category', '');
  v_site text := nullif(payload ->> 'site', '');
  v_request_type text := nullif(payload ->> 'request_type', '');
  v_snapshot_id bigint;
begin
  if public.current_app_role() not in ('system_admin', 'admin_recruiter') then
    raise exception 'System admin or admin recruiter role is required.';
  end if;
  if v_week_start is null then raise exception 'Week start is required.'; end if;
  if v_category not in ('Week Start', 'Open', 'Filled', 'Total') then raise exception 'Invalid waterfall category.'; end if;
  if v_site is null then raise exception 'Site is required.'; end if;
  if v_request_type not in ('New', 'Replacement') then raise exception 'Invalid request type.'; end if;

  perform set_config('app.action', 'vacancy_snapshot:upsert', true);
  insert into public.vacancy_weekly_snapshots (
    week_start, waterfall_category, site, request_type, vacancy_count, updated_by
  )
  values (
    v_week_start,
    v_category,
    v_site,
    v_request_type,
    coalesce(nullif(payload ->> 'vacancy_count', '')::integer, 0),
    auth.uid()
  )
  on conflict (week_start, waterfall_category, site, request_type) do update set
    vacancy_count = excluded.vacancy_count,
    updated_by = excluded.updated_by
  returning snapshot_id into v_snapshot_id;

  return jsonb_build_object('ok', true, 'id', v_snapshot_id::text);
end;
$$;

revoke all on function public.app_upsert_position_group(jsonb) from public, anon;
revoke all on function public.app_create_group_match(jsonb) from public, anon;

grant execute on function public.app_upsert_requisition(jsonb) to authenticated;
grant execute on function public.app_insert_requisition_log(jsonb) to authenticated;
grant execute on function public.app_upsert_position_group(jsonb) to authenticated;
grant execute on function public.app_create_group_match(jsonb) to authenticated;
grant execute on function public.app_upsert_sourcing_weekly_update(jsonb) to authenticated;
grant execute on function public.app_upsert_candidate(jsonb) to authenticated;
grant execute on function public.app_insert_recruitment_log(jsonb) to authenticated;
grant execute on function public.app_insert_pipeline_passes(jsonb) to authenticated;
grant execute on function public.app_insert_test_maintenance(jsonb) to authenticated;
grant execute on function public.app_insert_pipeline_test_exit(jsonb) to authenticated;
grant execute on function public.app_upsert_offer(jsonb) to authenticated;
grant execute on function public.app_upsert_vacancy_weekly_snapshot(jsonb) to authenticated;

commit;
