create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'viewer' check (role in ('admin', 'recruiter', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.requisitions (
  doc_id text primary key,
  pr_approved_date date,
  site text not null,
  position text not null,
  department text not null,
  section text,
  level text,
  head_count integer not null default 1 check (head_count > 0),
  person_in_charge text,
  line_manager text,
  status text not null default 'ongoing' check (status in ('ongoing', 'filled', 'cancel')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.requisition_logs (
  log_id bigint generated by default as identity primary key,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  log_date date not null,
  status text not null check (status in ('ongoing', 'filled', 'cancel')),
  remark text,
  created_at timestamptz not null default now()
);

create table if not exists public.position_groups (
  group_id text primary key,
  group_position text not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_groups (
  doc_group_id text primary key,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  group_id text references public.position_groups(group_id) on delete set null,
  group_position text not null,
  channel_fb boolean not null default false,
  channel_jobthai boolean not null default false,
  channel_jobtopgun boolean not null default false,
  channel_jobdb boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (doc_id, group_id)
);

create table if not exists public.candidates (
  candidate_id text primary key,
  name text not null,
  phone_no text,
  doc_group_id text not null references public.document_groups(doc_group_id) on delete restrict,
  channel text,
  ref_name text,
  first_contact_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recruitment_logs (
  log_id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  log_date date not null,
  recruitment_process text not null check (
    recruitment_process in (
      'First Contact',
      'Phone Screen',
      'HR Interview',
      'Line Interview',
      'Test',
      'Reference Check',
      'Offer',
      'Rejected',
      'Withdrawn'
    )
  ),
  round integer not null default 1 check (round > 0),
  interviewer text,
  result smallint check (result in (0, 1)),
  remark text,
  created_at timestamptz not null default now()
);

create table if not exists public.offers (
  offer_id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(candidate_id) on delete cascade,
  doc_id text not null references public.requisitions(doc_id) on delete cascade,
  accepted_date date,
  first_working_date date,
  offered_type text,
  replaced text,
  remark text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (candidate_id, doc_id)
);

create table if not exists public.change_logs (
  log_id bigint generated by default as identity primary key,
  entity text not null,
  entity_id text not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  old_data jsonb,
  new_data jsonb
);

create index if not exists idx_requisition_logs_doc_id on public.requisition_logs(doc_id);
create index if not exists idx_document_groups_doc_id on public.document_groups(doc_id);
create index if not exists idx_candidates_doc_group_id on public.candidates(doc_group_id);
create index if not exists idx_recruitment_logs_candidate_id on public.recruitment_logs(candidate_id);
create index if not exists idx_offers_candidate_id on public.offers(candidate_id);
create index if not exists idx_change_logs_entity on public.change_logs(entity, entity_id);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_requisitions_updated_at on public.requisitions;
create trigger set_requisitions_updated_at before update on public.requisitions
for each row execute function public.set_updated_at();

drop trigger if exists set_position_groups_updated_at on public.position_groups;
create trigger set_position_groups_updated_at before update on public.position_groups
for each row execute function public.set_updated_at();

drop trigger if exists set_document_groups_updated_at on public.document_groups;
create trigger set_document_groups_updated_at before update on public.document_groups
for each row execute function public.set_updated_at();

drop trigger if exists set_candidates_updated_at on public.candidates;
create trigger set_candidates_updated_at before update on public.candidates
for each row execute function public.set_updated_at();

drop trigger if exists set_offers_updated_at on public.offers;
create trigger set_offers_updated_at before update on public.offers
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'role', ''), 'viewer')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'anon')
$$;

create or replace function public.is_recruitment_reader()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() in ('admin', 'recruiter', 'viewer')
$$;

create or replace function public.is_recruitment_writer()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() in ('admin', 'recruiter')
$$;

create or replace function public.assert_recruitment_writer()
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_recruitment_writer() then
    raise exception 'Recruiter or admin role is required.';
  end if;
end;
$$;

alter table public.profiles enable row level security;
alter table public.requisitions enable row level security;
alter table public.requisition_logs enable row level security;
alter table public.position_groups enable row level security;
alter table public.document_groups enable row level security;
alter table public.candidates enable row level security;
alter table public.recruitment_logs enable row level security;
alter table public.offers enable row level security;
alter table public.change_logs enable row level security;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin on public.profiles
for select to authenticated
using (id = auth.uid() or public.current_app_role() = 'admin');

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.current_app_role() = 'admin')
with check (public.current_app_role() = 'admin');

drop policy if exists requisitions_read on public.requisitions;
create policy requisitions_read on public.requisitions for select to authenticated using (public.is_recruitment_reader());
drop policy if exists requisition_logs_read on public.requisition_logs;
create policy requisition_logs_read on public.requisition_logs for select to authenticated using (public.is_recruitment_reader());
drop policy if exists position_groups_read on public.position_groups;
create policy position_groups_read on public.position_groups for select to authenticated using (public.is_recruitment_reader());
drop policy if exists document_groups_read on public.document_groups;
create policy document_groups_read on public.document_groups for select to authenticated using (public.is_recruitment_reader());
drop policy if exists candidates_read on public.candidates;
create policy candidates_read on public.candidates for select to authenticated using (public.is_recruitment_reader());
drop policy if exists recruitment_logs_read on public.recruitment_logs;
create policy recruitment_logs_read on public.recruitment_logs for select to authenticated using (public.is_recruitment_reader());
drop policy if exists offers_read on public.offers;
create policy offers_read on public.offers for select to authenticated using (public.is_recruitment_reader());
drop policy if exists change_logs_read on public.change_logs;
create policy change_logs_read on public.change_logs for select to authenticated using (public.is_recruitment_reader());

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select on public.requisitions to authenticated;
grant select on public.requisition_logs to authenticated;
grant select on public.position_groups to authenticated;
grant select on public.document_groups to authenticated;
grant select on public.candidates to authenticated;
grant select on public.recruitment_logs to authenticated;
grant select on public.offers to authenticated;
grant select on public.change_logs to authenticated;

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_action text;
  v_entity_id text;
  v_email text;
begin
  v_row := coalesce(to_jsonb(new), to_jsonb(old));
  v_entity_id := coalesce(
    v_row ->> 'doc_id',
    v_row ->> 'candidate_id',
    v_row ->> 'group_id',
    v_row ->> 'doc_group_id',
    v_row ->> 'offer_id',
    v_row ->> 'log_id',
    'unknown'
  );
  v_action := coalesce(nullif(current_setting('app.action', true), ''), lower(tg_op));
  v_email := coalesce(
    (select email from public.profiles where id = auth.uid()),
    auth.jwt() ->> 'email'
  );

  insert into public.change_logs (entity, entity_id, action, changed_by, changed_by_email, old_data, new_data)
  values (
    tg_table_name,
    v_entity_id,
    v_action,
    auth.uid(),
    v_email,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists audit_requisitions on public.requisitions;
create trigger audit_requisitions after insert or update or delete on public.requisitions
for each row execute function public.audit_row_change();

drop trigger if exists audit_requisition_logs on public.requisition_logs;
create trigger audit_requisition_logs after insert or update or delete on public.requisition_logs
for each row execute function public.audit_row_change();

drop trigger if exists audit_position_groups on public.position_groups;
create trigger audit_position_groups after insert or update or delete on public.position_groups
for each row execute function public.audit_row_change();

drop trigger if exists audit_document_groups on public.document_groups;
create trigger audit_document_groups after insert or update or delete on public.document_groups
for each row execute function public.audit_row_change();

drop trigger if exists audit_candidates on public.candidates;
create trigger audit_candidates after insert or update or delete on public.candidates
for each row execute function public.audit_row_change();

drop trigger if exists audit_recruitment_logs on public.recruitment_logs;
create trigger audit_recruitment_logs after insert or update or delete on public.recruitment_logs
for each row execute function public.audit_row_change();

drop trigger if exists audit_offers on public.offers;
create trigger audit_offers after insert or update or delete on public.offers
for each row execute function public.audit_row_change();

create or replace function public.next_prefixed_id(p_table text, p_column text, p_prefix text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_next integer;
begin
  execute format(
    'select coalesce(max(nullif(substring(%1$I from %2$L), '''')::integer), 0) + 1 from public.%3$I where %1$I ~ %4$L',
    p_column,
    p_prefix || '-([0-9]+)',
    p_table,
    '^' || p_prefix || '-[0-9]+$'
  ) into v_next;

  return p_prefix || '-' || lpad(v_next::text, 4, '0');
end;
$$;

create or replace function public.refresh_requisition_status(p_doc_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_head_count integer;
  v_status text;
  v_accepted_count integer;
  v_next_status text;
begin
  select head_count, status into v_head_count, v_status
  from public.requisitions
  where doc_id = p_doc_id;

  if not found or v_status = 'cancel' then
    return;
  end if;

  select count(*) into v_accepted_count
  from public.offers
  where doc_id = p_doc_id and accepted_date is not null;

  v_next_status := case when v_accepted_count >= v_head_count then 'filled' else 'ongoing' end;

  if v_next_status <> v_status then
    update public.requisitions
    set status = v_next_status
    where doc_id = p_doc_id;
  end if;
end;
$$;

create or replace function public.app_upsert_requisition(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text := coalesce(payload ->> 'mode', 'new');
  v_doc_id text := nullif(payload ->> 'doc_id', '');
  v_exists boolean;
  v_status text := coalesce(nullif(payload ->> 'status', ''), 'ongoing');
begin
  perform public.assert_recruitment_writer();
  if v_mode not in ('new', 'change') then raise exception 'mode must be new or change'; end if;
  if v_status not in ('ongoing', 'cancel') then raise exception 'Requisition status can only be ongoing or cancel. Filled is automatic.'; end if;

  select exists(select 1 from public.requisitions where doc_id = v_doc_id) into v_exists;
  if v_mode = 'new' and v_exists then raise exception 'Requisition Doc ID already exists. Switch to Change mode to edit it.'; end if;
  if v_mode = 'change' and not v_exists then raise exception 'Requisition Doc ID does not exist. Switch to New mode to create it.'; end if;

  perform set_config('app.action', 'requisition:' || v_mode, true);

  insert into public.requisitions (
    doc_id, pr_approved_date, site, position, department, section, level,
    head_count, person_in_charge, line_manager, status
  )
  values (
    v_doc_id,
    nullif(payload ->> 'pr_approved_date', '')::date,
    nullif(payload ->> 'site', ''),
    nullif(payload ->> 'position', ''),
    nullif(payload ->> 'department', ''),
    nullif(payload ->> 'section', ''),
    nullif(payload ->> 'level', ''),
    coalesce(nullif(payload ->> 'head_count', '')::integer, 1),
    nullif(payload ->> 'person_in_charge', ''),
    nullif(payload ->> 'line_manager', ''),
    v_status
  )
  on conflict (doc_id) do update set
    pr_approved_date = excluded.pr_approved_date,
    site = excluded.site,
    position = excluded.position,
    department = excluded.department,
    section = excluded.section,
    level = excluded.level,
    head_count = excluded.head_count,
    person_in_charge = excluded.person_in_charge,
    line_manager = excluded.line_manager,
    status = excluded.status;

  perform set_config('app.action', 'auto-status', true);
  perform public.refresh_requisition_status(v_doc_id);
  return jsonb_build_object('ok', true, 'id', v_doc_id);
end;
$$;

create or replace function public.app_insert_requisition_log(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doc_id text := nullif(payload ->> 'doc_id', '');
  v_status text := nullif(payload ->> 'status', '');
begin
  perform public.assert_recruitment_writer();
  if v_status not in ('ongoing', 'filled', 'cancel') then raise exception 'Status must be ongoing, filled, or cancel.'; end if;

  perform set_config('app.action', 'requisition:status', true);
  insert into public.requisition_logs (doc_id, log_date, status, remark)
  values (v_doc_id, nullif(payload ->> 'log_date', '')::date, v_status, nullif(payload ->> 'remark', ''));

  update public.requisitions set status = v_status where doc_id = v_doc_id;
  perform set_config('app.action', 'auto-status', true);
  perform public.refresh_requisition_status(v_doc_id);
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.app_upsert_position_group(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text := coalesce(payload ->> 'mode', 'new');
  v_group_id text := nullif(payload ->> 'group_id', '');
  v_exists boolean;
begin
  perform public.assert_recruitment_writer();
  if v_mode = 'new' then
    v_group_id := public.next_prefixed_id('position_groups', 'group_id', 'GRP');
  elsif v_group_id is null then
    raise exception 'Group ID is required in Change mode.';
  end if;

  select exists(select 1 from public.position_groups where group_id = v_group_id) into v_exists;
  if v_mode = 'new' and v_exists then raise exception 'Group ID already exists. Switch to Change mode to edit it.'; end if;
  if v_mode = 'change' and not v_exists then raise exception 'Group ID does not exist. Switch to New mode to create it.'; end if;

  perform set_config('app.action', 'position_group:' || v_mode, true);
  insert into public.position_groups (group_id, group_position, channel_fb, channel_jobthai, channel_jobtopgun, channel_jobdb)
  values (
    v_group_id,
    nullif(payload ->> 'group_position', ''),
    coalesce((payload ->> 'channel_fb')::boolean, false),
    coalesce((payload ->> 'channel_jobthai')::boolean, false),
    coalesce((payload ->> 'channel_jobtopgun')::boolean, false),
    coalesce((payload ->> 'channel_jobdb')::boolean, false)
  )
  on conflict (group_id) do update set
    group_position = excluded.group_position,
    channel_fb = excluded.channel_fb,
    channel_jobthai = excluded.channel_jobthai,
    channel_jobtopgun = excluded.channel_jobtopgun,
    channel_jobdb = excluded.channel_jobdb;

  return jsonb_build_object('ok', true, 'id', v_group_id);
end;
$$;

create or replace function public.app_create_group_match(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doc_id text := nullif(payload ->> 'doc_id', '');
  v_group_id text := nullif(payload ->> 'group_id', '');
  v_doc_group_id text;
  v_group public.position_groups%rowtype;
begin
  perform public.assert_recruitment_writer();
  select * into v_group from public.position_groups where group_id = v_group_id;
  if not found then raise exception 'Group ID does not exist.'; end if;
  if exists(select 1 from public.document_groups where doc_id = v_doc_id and group_id = v_group_id) then
    raise exception 'This requisition is already matched to that group.';
  end if;

  v_doc_group_id := public.next_prefixed_id('document_groups', 'doc_group_id', 'DGRP');
  perform set_config('app.action', 'document_group:new', true);
  insert into public.document_groups (
    doc_group_id, doc_id, group_id, group_position, channel_fb, channel_jobthai, channel_jobtopgun, channel_jobdb
  )
  values (
    v_doc_group_id, v_doc_id, v_group_id, v_group.group_position,
    v_group.channel_fb, v_group.channel_jobthai, v_group.channel_jobtopgun, v_group.channel_jobdb
  );

  return jsonb_build_object('ok', true, 'id', v_doc_group_id);
end;
$$;

create or replace function public.app_upsert_candidate(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text := coalesce(payload ->> 'mode', 'new');
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_exists boolean;
begin
  perform public.assert_recruitment_writer();
  if v_mode = 'new' then
    v_candidate_id := public.next_prefixed_id('candidates', 'candidate_id', 'CAN');
  elsif v_candidate_id is null then
    raise exception 'Candidate ID is required in Change mode.';
  end if;

  select exists(select 1 from public.candidates where candidate_id = v_candidate_id) into v_exists;
  if v_mode = 'new' and v_exists then raise exception 'Candidate ID already exists. Switch to Change mode to edit it.'; end if;
  if v_mode = 'change' and not v_exists then raise exception 'Candidate ID does not exist. Switch to New mode to create it.'; end if;

  perform set_config('app.action', 'candidate:' || v_mode, true);
  insert into public.candidates (candidate_id, name, phone_no, doc_group_id, channel, ref_name, first_contact_date)
  values (
    v_candidate_id,
    nullif(payload ->> 'name', ''),
    nullif(payload ->> 'phone_no', ''),
    nullif(payload ->> 'doc_group_id', ''),
    nullif(payload ->> 'channel', ''),
    nullif(payload ->> 'ref_name', ''),
    nullif(payload ->> 'first_contact_date', '')::date
  )
  on conflict (candidate_id) do update set
    name = excluded.name,
    phone_no = excluded.phone_no,
    doc_group_id = excluded.doc_group_id,
    channel = excluded.channel,
    ref_name = excluded.ref_name,
    first_contact_date = excluded.first_contact_date;

  return jsonb_build_object('ok', true, 'id', v_candidate_id);
end;
$$;

create or replace function public.app_insert_recruitment_log(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_stage text := nullif(payload ->> 'recruitment_process', '');
  v_result smallint := nullif(payload ->> 'result', '')::smallint;
  v_source text := coalesce(nullif(payload ->> 'source', ''), 'manual');
  v_current_stage text;
  v_current_index integer;
  v_next_index integer;
  v_log_id bigint;
begin
  perform public.assert_recruitment_writer();

  if v_source = 'pipeline' then
    select recruitment_process into v_current_stage
    from public.recruitment_logs
    where candidate_id = v_candidate_id
    order by log_id desc
    limit 1;

    v_current_index := coalesce(array_position(array[
      'First Contact', 'Phone Screen', 'HR Interview', 'Line Interview', 'Test',
      'Reference Check', 'Offer', 'Rejected', 'Withdrawn'
    ], v_current_stage), 0);
    v_next_index := coalesce(array_position(array[
      'First Contact', 'Phone Screen', 'HR Interview', 'Line Interview', 'Test',
      'Reference Check', 'Offer', 'Rejected', 'Withdrawn'
    ], v_stage), 0);

    if v_next_index <= v_current_index then
      raise exception 'Pipeline cards can move forward only.';
    end if;
  end if;

  perform set_config('app.action', 'recruitment_log:new', true);
  insert into public.recruitment_logs (candidate_id, log_date, recruitment_process, round, interviewer, result, remark)
  values (
    v_candidate_id,
    nullif(payload ->> 'log_date', '')::date,
    v_stage,
    coalesce(nullif(payload ->> 'round', '')::integer, 1),
    nullif(payload ->> 'interviewer', ''),
    v_result,
    nullif(payload ->> 'remark', '')
  )
  returning log_id into v_log_id;

  update public.candidates set updated_at = now() where candidate_id = v_candidate_id;
  return jsonb_build_object('ok', true, 'id', v_log_id::text);
end;
$$;

create or replace function public.app_upsert_offer(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text := coalesce(payload ->> 'mode', 'new');
  v_candidate_id text := nullif(payload ->> 'candidate_id', '');
  v_doc_id text := nullif(payload ->> 'doc_id', '');
  v_exists boolean;
  v_offer_id bigint;
begin
  perform public.assert_recruitment_writer();
  select exists(select 1 from public.offers where candidate_id = v_candidate_id and doc_id = v_doc_id) into v_exists;
  if v_mode = 'new' and v_exists then raise exception 'This offer already exists. Switch to Change mode to edit it.'; end if;
  if v_mode = 'change' and not v_exists then raise exception 'This offer does not exist. Switch to New mode to create it.'; end if;

  perform set_config('app.action', 'offer:' || v_mode, true);
  insert into public.offers (candidate_id, doc_id, accepted_date, first_working_date, offered_type, replaced, remark)
  values (
    v_candidate_id,
    v_doc_id,
    nullif(payload ->> 'accepted_date', '')::date,
    nullif(payload ->> 'first_working_date', '')::date,
    nullif(payload ->> 'offered_type', ''),
    nullif(payload ->> 'replaced', ''),
    nullif(payload ->> 'remark', '')
  )
  on conflict (candidate_id, doc_id) do update set
    accepted_date = excluded.accepted_date,
    first_working_date = excluded.first_working_date,
    offered_type = excluded.offered_type,
    replaced = excluded.replaced,
    remark = excluded.remark
  returning offer_id into v_offer_id;

  perform set_config('app.action', 'auto-status', true);
  perform public.refresh_requisition_status(v_doc_id);
  return jsonb_build_object('ok', true, 'id', v_offer_id::text);
end;
$$;

grant execute on function public.app_upsert_requisition(jsonb) to authenticated;
grant execute on function public.app_insert_requisition_log(jsonb) to authenticated;
grant execute on function public.app_upsert_position_group(jsonb) to authenticated;
grant execute on function public.app_create_group_match(jsonb) to authenticated;
grant execute on function public.app_upsert_candidate(jsonb) to authenticated;
grant execute on function public.app_insert_recruitment_log(jsonb) to authenticated;
grant execute on function public.app_upsert_offer(jsonb) to authenticated;
